Repository cert-manager/cert-manager, pull requests merged in 2018-08, with the labels that each got.

#795 Move API types into separate files
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/types_issuer.go
Labels: approved, lgtm, release-note-none, size/XL

#796 Refactor API type names
  docs/generated/reference/output/reference/api-docs/index.html
  docs/generated/reference/output/reference/api-docs/navData.js
  pkg/apis/certmanager/v1alpha1/helpers.go
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/certificate.go
  pkg/apis/certmanager/validation/certificate_for_issuer_test.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
  pkg/issuer/acme/http/pod_test.go
  pkg/issuer/acme/http/service_test.go
  pkg/issuer/acme/prepare.go
  pkg/issuer/acme/prepare_test.go
  test/e2e/certificate/certificate_acme_dns01.go
  test/util/generate/certificate.go
  test/util/util.go
Labels: approved, lgtm, release-note-none, size/XL

#797 Refactor ACME client construction into dedicated ACME package
  pkg/acme/acme.go
  pkg/acme/client/fake.go
  pkg/acme/client/interfaces.go
  pkg/acme/client/middleware/logger.go
  pkg/issuer/acme/acme.go
  pkg/issuer/acme/issue.go
  pkg/issuer/acme/prepare.go
  pkg/issuer/acme/setup.go
  pkg/issuer/acme/util_test.go
Labels: approved, lgtm, release-note-none, size/L

#772 Add documentation on creating DNS01 providers
  docs/devel/dns01-providers.rst
  docs/devel/index.rst
Labels: approved, kind/documentation, lgtm, release-note-none, size/M

#799 Change leader election duration defaults to be less chatty
  cmd/controller/app/options/options.go
Labels: approved, lgtm, release-note, size/XS

#801 Add RenewBeforeExpiryDuration option to controller context
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/controller/certificates/sync.go
  pkg/controller/context.go
  pkg/controller/helper.go
Labels: approved, lgtm, release-note, size/M

#803 Update 'troubleshooting' and 'current status' README sections
  README.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/M

#810 Add additional issue template types
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/M

#805 Automated cherry pick of #801 #800
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/controller/certificates/controller.go
  pkg/controller/certificates/sync.go
  pkg/controller/context.go
  pkg/issuer/acme/acme.go
  pkg/issuer/acme/client/fake.go
  pkg/issuer/acme/client/interfaces.go
  pkg/issuer/acme/client/middleware/logger.go
  pkg/issuer/acme/issue.go
  pkg/issuer/acme/util_test.go
  pkg/issuer/context.go
  pkg/util/pki/generate.go
  pkg/util/pki/generate_test.go
  third_party/crypto/acme/acme.go
Labels: approved, lgtm, release-note, size/L

#807 Catch edge case where the CN and DNSNames on a Certificate have been reordered
  pkg/issuer/acme/issue.go
Labels: approved, lgtm, release-note-none, size/XS

#814 Automated cherry pick of #807 #811
  pkg/issuer/acme/issue.go
  pkg/util/pki/csr.go
Labels: approved, lgtm, release-note-none, size/S

#811 Don't bundle the CA certificate when selfsigned
  pkg/util/pki/csr.go
Labels: approved, lgtm, release-note, size/S

#815 Bump image version for v0.4.1
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#816 Catch and return dns query error in DNS01Record
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/azuredns/azuredns.go
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/route53/route53.go
  pkg/issuer/acme/dns/util/dns.go
Labels: approved, lgtm, release-note-none, size/M

#824 Add details on DCO sign-off
  CONTRIBUTING.md
  docs/devel/dco-sign-off.rst
  docs/devel/index.rst
Labels: approved, lgtm, release-note-none, size/L

#825 fix: plumb dns servers into more areas
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/akamai/akamai_test.go
  pkg/issuer/acme/dns/azuredns/azuredns.go
  pkg/issuer/acme/dns/azuredns/azuredns_test.go
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/acme/dns/clouddns/clouddns_test.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/cloudflare/cloudflare_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
  pkg/issuer/acme/dns/route53/route53.go
  pkg/issuer/acme/dns/route53/route53_test.go
  pkg/issuer/acme/dns/util/dns.go
  pkg/issuer/acme/dns/util/wait.go
  pkg/issuer/acme/dns/util/wait_test.go
  pkg/issuer/acme/dns/util_test.go
Labels: approved, lgtm, release-note-none, size/L

#831 Fix issue causing existing ingresses to not be cleaned up properly
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
Labels: approved, lgtm, release-note, size/M

#658 Add 'isCA' field to Certificate spec
  docs/generated/reference/output/reference/api-docs/index.html
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/validation/certificate_for_issuer.go
  pkg/util/pki/csr.go
Labels: approved, lgtm, release-note, size/S

#823 chart: annotate all CRDs with "crd-install" hook
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/certificate-crd.yaml
  contrib/charts/cert-manager/templates/clusterissuer-crd.yaml
  contrib/charts/cert-manager/templates/issuer-crd.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#787 Add ACME-DNS as a DNS-01 Provider
  Gopkg.lock
  docs/generated/reference/output/reference/api-docs/index.html
  docs/generated/reference/output/reference/api-docs/navData.js
  docs/reference/issuers/acme/dns01.rst
  pkg/apis/certmanager/v1alpha1/types_issuer.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/issuer.go
  pkg/issuer/acme/dns/acmedns/acmedns.go
  pkg/issuer/acme/dns/acmedns/acmedns_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/util_test.go
  vendor/github.com/cpu/goacmedns/.errcheck_exclude
  vendor/github.com/cpu/goacmedns/.gitignore
  vendor/github.com/cpu/goacmedns/.travis.yml
  vendor/github.com/cpu/goacmedns/LICENSE
  vendor/github.com/cpu/goacmedns/README.md
  vendor/github.com/cpu/goacmedns/account.go
  vendor/github.com/cpu/goacmedns/client.go
  vendor/github.com/cpu/goacmedns/client_test.go
  vendor/github.com/cpu/goacmedns/storage.go
  vendor/github.com/cpu/goacmedns/storage_test.go
Labels: approved, lgtm, release-note, size/XXL

#851 Run hack/update-deploy-gen.sh
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/S

#849 Fix cloudflare provider failing on cleanup if no record is found
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
Labels: approved, lgtm, release-note, size/XS

#853 Bump helm version on Gitlab CI
  .gitlab-ci.yml
Labels: approved, lgtm, release-note-none, size/XS
