Repository cert-manager/cert-manager, pull requests merged in 2018-07, with the labels that each got.

#695 Add doc on secret references for cluster issuers
  docs/reference/clusterissuers.rst
Labels: approved, lgtm, release-note-none, size/XS

#698 Support the new ACMEv2 "ready" order status
  pkg/issuer/acme/prepare.go
  third_party/crypto/acme/types.go
Labels: approved, lgtm, release-note, size/XS

#700 Automated cherry pick of #686 #695 #698
  docs/reference/clusterissuers.rst
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
  pkg/issuer/acme/prepare.go
  third_party/crypto/acme/types.go
Labels: approved, lgtm, release-note-none, size/L

#703 Use kubernetes-helm/chart-testing scripts to verify helm chart
  hack/verify-chart-version.sh
  test/chart/.testenv
  test/chart/chart_test.sh
  test/chart/etc/chart_schema.yaml
  test/chart/etc/lintconf.yaml
  test/chart/lib/chartlib.sh
Labels: approved, lgtm, release-note-none, size/XL

#704 Automated cherry pick of #703
  hack/verify-chart-version.sh
  test/chart/.testenv
  test/chart/chart_test.sh
  test/chart/etc/chart_schema.yaml
  test/chart/etc/lintconf.yaml
  test/chart/lib/chartlib.sh
Labels: approved, lgtm, release-note-none, size/XL

#702 Bump Helm chart for v0.3.2
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#708 Prevent panics in v1alpha1 helpers.go
  pkg/apis/certmanager/v1alpha1/helpers.go
Labels: approved, lgtm, release-note, size/S

#709 Automated cherry pick of #708 upstream release 0.3
  pkg/apis/certmanager/v1alpha1/helpers.go
Labels: approved, lgtm, release-note-none, size/S

#680 Allow setting http_proxy and https_proxy in cert-manager deployment
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note, size/M

#507 Fix AWS DNS policy example
  docs/reference/issuers/acme/dns01.rst
Labels: approved, area/provider-acme, lgtm, release-note-none, size/XS

#718 Add log message showing git tag and commit during startup
  cmd/controller/start.go
Labels: approved, lgtm, release-note-none, size/XS

#719 Add certificate-name label to created secrets
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/controller/certificates/sync.go
  test/e2e/framework/certificate.go
Labels: approved, lgtm, release-note, size/S

#720 route53: update managed by DNS record comment
  pkg/issuer/acme/dns/route53/route53.go
Labels: approved, lgtm, release-note-none, size/XS

#707 Merge latest changes from upstream crypto/acme library
  third_party/crypto/acme/acme.go
  third_party/crypto/acme/integration_test.go
  third_party/crypto/acme/types.go
Labels: approved, lgtm, release-note-none, size/M

#622 Add auth.istio.io annotation to ACME HTTP01 service
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/service.go
Labels: approved, lgtm, release-note, size/S

#612 Vault: configurable appRole authentication path
  docs/generated/reference/output/reference/api-docs/index.html
  docs/tutorials/vault/creating-vault-issuers.rst
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/issuer/vault/issue.go
  pkg/issuer/vault/setup.go
  test/e2e/certificate/certificate_vault.go
  test/e2e/issuer/issuer_vault.go
  test/util/util.go
  test/util/vault/util.go
Labels: approved, area/provider-vault, lgtm, release-note, size/L

#717 Add --controllers flag to set which controllers are run
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, lgtm, release-note, size/M

#726 Add link to selfsigned issuer docs
  docs/reference/issuers.rst
Labels: approved, lgtm, release-note-none, size/XS

#727 Automated cherry pick of #726 upstream release 0.4
  docs/reference/issuers.rst
Labels: approved, lgtm, release-note-none, size/XS

#722 Add keyAlgorithm and keySize fields to Certificates, and support ECDSA keys
  docs/generated/reference/output/reference/api-docs/index.html
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/apis/certmanager/validation/certificate.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/issuer/acme/acme.go
  pkg/issuer/acme/issue.go
  pkg/issuer/acme/setup.go
  pkg/issuer/ca/issue.go
  pkg/issuer/ca/renew.go
  pkg/issuer/selfsigned/issue.go
  pkg/issuer/selfsigned/renew.go
  pkg/issuer/vault/issue.go
  pkg/util/kube/pki.go
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/generate.go
  pkg/util/pki/generate_test.go
  pkg/util/pki/parse.go
  pkg/util/pki/parse_test.go
Labels: approved, lgtm, release-note, size/XL

#747 hack/verify: also include 'dep version' output
  hack/verify-deps.sh
Labels: approved, lgtm, release-note-none, size/XS

#744 Add e2e test to ensure changing dnsNames on an ACME certificate triggers a re-issue
  test/e2e/certificate/certificate_acme.go
  test/e2e/certificate/certificate_acme_dns01.go
  test/e2e/certificate/certificate_ca.go
  test/e2e/certificate/certificate_selfsigned.go
  test/e2e/certificate/certificate_vault.go
  test/e2e/e2e.go
  test/e2e/framework/certificate.go
  test/e2e/ingress/certificate_acme.go
  test/util/util.go
Labels: approved, lgtm, release-note-none, size/L

#750 clouddns: find hosted zone for challenge record
  pkg/issuer/acme/dns/clouddns/clouddns.go
Labels: approved, lgtm, release-note-none, size/XS

#751 Automated cherry pick of #750
  pkg/issuer/acme/dns/clouddns/clouddns.go
Labels: approved, lgtm, release-note, size/XS

#746 issuer/route53: fix delete for 'NotExist' errors
  Gopkg.lock
  pkg/issuer/acme/dns/route53/route53.go
Labels: approved, lgtm, release-note, size/S

#670 add support CNAME for dns-01 challenge
  pkg/issuer/acme/dns/util/dns.go
  pkg/issuer/acme/dns/util/wait.go
Labels: approved, lgtm, release-note, size/M

#755 Automated cherry pick of #754
  pkg/issuer/acme/dns/clouddns/clouddns.go
Labels: approved, lgtm, size/XS

#748 Document project field for Google CloudDNS provider
  docs/reference/issuers/acme/dns01.rst
Labels: approved, lgtm, release-note-none, size/XS

#753 Automated cherry pick of #746
  Gopkg.lock
  pkg/issuer/acme/dns/route53/route53.go
Labels: approved, lgtm, size/S

#754 clouddns: use fqdn for challenge cleanup
  pkg/issuer/acme/dns/clouddns/clouddns.go
Labels: approved, lgtm, release-note, size/XS

#759 Add note about http01 and wildcard certificates to docs
  docs/reference/issuers.rst
  docs/reference/issuers/acme/http01.rst
Labels: approved, lgtm, release-note-none, size/XS

#763 Automated cherry pick of #759
  docs/reference/issuers.rst
  docs/reference/issuers/acme/http01.rst
Labels: approved, lgtm, release-note-none, size/XS

#764 Wait for ACME Orders to be in 'ready' state before attempting finalization
  contrib/charts/pebble/Chart.yaml
  contrib/charts/pebble/values.yaml
  pkg/issuer/acme/issue.go
  test/chart/.testenv
Labels: approved, lgtm, release-note, size/S

#765 Automated cherry pick of #764
  contrib/charts/pebble/Chart.yaml
  contrib/charts/pebble/values.yaml
  pkg/issuer/acme/issue.go
  test/chart/.testenv
Labels: approved, lgtm, size/S

#761 Add base of issuer-specific validation to certificates at runtime
  pkg/apis/certmanager/validation/certificate_for_issuer.go
  pkg/apis/certmanager/validation/certificate_for_issuer_test.go
  pkg/controller/certificates/sync.go
  pkg/issuer/const.go
  pkg/issuer/factory.go
Labels: approved, lgtm, release-note, size/L

#768 Add github label for DNS01 providers
  labels.yaml
Labels: approved, lgtm, release-note-none, size/XS

#769 helm chart: remove endpoints from rbac resources
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/rbac.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#770 Add OWNERS files to auto-label PRs.
  docs/OWNERS
  pkg/apis/OWNERS
  pkg/issuer/acme/OWNERS
  pkg/issuer/acme/dns/OWNERS
  pkg/issuer/ca/OWNERS
  pkg/issuer/selfsigned/OWNERS
  pkg/issuer/vault/OWNERS
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/S
