Repository cert-manager/cert-manager, pull requests merged in 2018-11, with the labels that each got.

#1036 Remove crd-install annotation from Challenges and Orders
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/challenge-crd.yaml
  contrib/charts/cert-manager/templates/order-crd.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1030 Automated cherry pick of #981 #1017
  docs/tutorials/acme/migrating-from-kube-lego.rst
  pkg/controller/clusterissuers/controller.go
  pkg/controller/ingress-shim/controller.go
  pkg/controller/issuers/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1041 Remove hardcoded image #1039
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/templates/ca-sync.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1031 Automated cherry pick of #998
  pkg/issuer/acme/setup.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#738 Configurable ACME Annotation
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/controller/context.go
  pkg/controller/ingress-shim/controller.go
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1047 Stamp docker images with current timestamp using Bazel
  cmd/acmesolver/BUILD.bazel
  cmd/controller/BUILD.bazel
  cmd/webhook/BUILD.bazel
  hack/def.bzl
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1040 Use go_sdk gofmt instead of goimports
  WORKSPACE
  hack/BUILD.bazel
  hack/bin/BUILD.bazel
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
  pkg/controller/acmeorders/sync_test.go
  pkg/controller/ingress-shim/sync_test.go
  pkg/util/version_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1046 Revert "Remove pkg/logs package"
  BUILD.bazel
  cmd/acmesolver/BUILD.bazel
  cmd/acmesolver/main.go
  cmd/controller/BUILD.bazel
  cmd/controller/main.go
  cmd/webhook/BUILD.bazel
  cmd/webhook/main.go
  pkg/logs/BUILD.bazel
  pkg/logs/logs.go
  test/e2e/BUILD.bazel
  test/e2e/e2e_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1043 Automated cherry pick of #1033
  pkg/issuer/acme/dns/util/wait.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, size/S

#1048 Fix invalid secret name used in certificates controller
  pkg/controller/certificates/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1049 Add Certificate and Issuer unit gen functions
  test/unit/gen/BUILD.bazel
  test/unit/gen/certificate.go
  test/unit/gen/issuer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1050 Bump project to use Go 1.11.2
  BUILD.bazel
  WORKSPACE
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/ingress-shim/sync_test.go
  pkg/issuer/vault/issue.go
  test/e2e/framework/addon/vault/setup.go
  third_party/crypto/acme/acme.go
  vendor/github.com/golang/protobuf/ptypes/BUILD.bazel
  vendor/github.com/googleapis/gnostic/OpenAPIv2/BUILD.bazel
  vendor/github.com/googleapis/gnostic/compiler/BUILD.bazel
  vendor/github.com/googleapis/gnostic/extensions/BUILD.bazel
  vendor/google.golang.org/genproto/googleapis/rpc/status/BUILD.bazel
  vendor/google.golang.org/grpc/status/BUILD.bazel
  vendor/google.golang.org/grpc/transport/BUILD.bazel
Labels: approved, area/provider-vault, dco-signoff: yes, lgtm, release-note, size/M

#1053 Bump CI image used on GitLab
  .gitlab-ci.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none

#1012 Add e2e test verifying we can obtain ECDSA keys from RSA CA issuers
  pkg/issuer/ca/BUILD.bazel
  pkg/issuer/ca/issue.go
  pkg/issuer/ca/issue_test.go
  pkg/issuer/ca/util_test.go
  pkg/util/pki/csr.go
  test/e2e/suite/issuers/ca/certificate.go
  test/unit/gen/certificate.go
  test/util/util.go
Labels: approved, area/provider-ca, dco-signoff: yes, lgtm, release-note-none, size/L

#1052 Re-enable webhook during e2e tests and fix panic on start
  cmd/webhook/BUILD.bazel
  cmd/webhook/main.go
  test/e2e/framework/helper/pod_start.go
  test/fixtures/cert-manager-values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1057 Bump Helm chart version to canary on master
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1058 Fix GitLab build use of APP_VERSION
  .gitlab-ci.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1059 Fire Events when challenges succeed or fail
  pkg/controller/acmechallenges/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1065 Docs cleanup
  docs/devel/dco-sign-off.rst
  docs/devel/generate-docs.rst
  docs/reference/issuers/acme/http01.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/S

#1066 adding files for quickstart
  docs/tutorials/quick-start/echoserver/deployment.yaml
  docs/tutorials/quick-start/echoserver/ingress-tls.yaml
  docs/tutorials/quick-start/echoserver/ingress.yaml
  docs/tutorials/quick-start/echoserver/service.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#1032 Skip re-checking ACME account status if Issuer is ready and URL hosts match
  pkg/acme/acme.go
  pkg/issuer/acme/setup.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note-none, size/L

#1073 Mark issuer as invalid when parsing URLs fails
  pkg/issuer/acme/setup.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note-none, size/S

#1074 Automated cherry pick of #1032 #1073
  pkg/acme/acme.go
  pkg/issuer/acme/setup.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note-none, size/L

#1063 Bump kind to latest HEAD
  WORKSPACE
  hack/ci/lib/cluster_create.sh
  hack/ci/lib/lib.sh
  test/fixtures/kind-config.yaml
  test/fixtures/kind/config-v1alpha2.yaml
  test/fixtures/kind/config-v1alpha3.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1071 acmeorders: instantiate real clock
  pkg/controller/acmeorders/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#893 Configurable issuer duration and renewBefore Take 2
  docs/generated/reference/output/reference/api-docs/index.html
  docs/generated/reference/output/reference/api-docs/navData.js
  docs/reference/certificates.rst
  pkg/apis/certmanager/v1alpha1/BUILD.bazel
  pkg/apis/certmanager/v1alpha1/const.go
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/BUILD.bazel
  pkg/apis/certmanager/validation/certificate.go
  pkg/apis/certmanager/validation/certificate_for_issuer.go
  pkg/apis/certmanager/validation/certificate_for_issuer_test.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/apis/certmanager/validation/issuer.go
  pkg/controller/BUILD.bazel
  pkg/controller/certificates/BUILD.bazel
  pkg/controller/certificates/sync.go
  pkg/controller/certificates/sync_test.go
  pkg/controller/helper.go
  pkg/issuer/acme/issue.go
  pkg/issuer/vault/issue.go
  pkg/util/pki/csr.go
  pkg/util/pki/generate_test.go
  test/e2e/framework/BUILD.bazel
  test/e2e/framework/framework.go
  test/e2e/suite/issuers/acme/certificate/http01.go
  test/e2e/suite/issuers/ca/BUILD.bazel
  test/e2e/suite/issuers/ca/certificate.go
  test/e2e/suite/issuers/selfsigned/BUILD.bazel
  test/e2e/suite/issuers/selfsigned/certificate.go
  test/e2e/suite/issuers/vault/certificate/BUILD.bazel
  test/e2e/suite/issuers/vault/certificate/approle.go
  test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go
  test/e2e/suite/issuers/vault/issuer.go
  test/util/generate/certificate.go
  test/util/util.go
Labels: approved, area/provider-acme, area/provider-vault, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XL, tide/squash

#1008 Move reference-docs generation tools into docs/ subdir
  WORKSPACE
  docs/generated/reference/BUILD.bazel
  docs/generated/reference/generate/BUILD.bazel
  docs/generated/reference/generate/bin/BUILD.bazel
  docs/generated/reference/generate/bin/package-lock.json
  docs/generated/reference/generate/config.yaml
  docs/generated/reference/generate/go_openapi/BUILD.bazel
  docs/generated/reference/generate/go_openapi/def.bzl
  docs/generated/reference/generate/go_openapi/doc.go
  docs/generated/reference/generate/json_swagger/BUILD.bazel
  docs/generated/reference/generate/json_swagger/main.go
  docs/generated/reference/generate/static_includes/BUILD.bazel
  docs/generated/reference/generate/static_includes/_certmanager.md
  docs/generated/reference/generate/static_includes/_definitions.md
  docs/generated/reference/generate/static_includes/_oldversions.md
  docs/generated/reference/generate/static_includes/_overview.md
  hack/BUILD.bazel
  hack/bin/BUILD.bazel
  hack/update-bazel.sh
  hack/update-reference-docs.sh
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1080 Bump manifests for v0.5.1
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1075 changes to add a NotAfter field to the cert status
  docs/generated/reference/output/reference/api-docs/index.html
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/certificates/sync.go
  test/util/util.go
Labels: approved, area/provider-acme, area/provider-vault, dco-signoff: yes, kind/documentation, lgtm, release-note, size/S

#1082 Fix bug with ingress path cleanup
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
Labels: approved, area/provider-acme, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#1085 Automated cherry pick of #1082
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, size/L

#1087 Bump manifests for v0.5.2
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1086 Fix dep failures by running update-bazel
  WORKSPACE
  hack/BUILD.bazel
  hack/bin/BUILD.bazel
  hack/update-bazel.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1091 chart: allow deployment strategy customization
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/templates/deployment.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1023 Schedule certificate renewal at the end of Certificate Sync function
  pkg/controller/certificates/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1098 Retry after a fixed 5s if self check is failing & adjust all controllers to use same rate limiter
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmechallenges/scheduler/controller.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmechallenges/sync_test.go
  pkg/controller/acmeorders/controller.go
  pkg/controller/certificates/controller.go
  pkg/controller/clusterissuers/controller.go
  pkg/controller/ingress-shim/controller.go
  pkg/controller/issuers/controller.go
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1055 Add quick-start guide for nginx ingress controller
  .gitignore
  README.md
  docs/devel/generate-docs.rst
  docs/devel/index.rst
  docs/tutorials/acme/migrating-from-kube-lego.rst
  docs/tutorials/index.rst
  docs/tutorials/quick-start/echoserver/ingress-tls.yaml
  docs/tutorials/quick-start/echoserver/ingress.yaml
  docs/tutorials/quick-start/example/deployment.yaml
  docs/tutorials/quick-start/example/ingress-tls-final.yaml
  docs/tutorials/quick-start/example/ingress-tls.yaml
  docs/tutorials/quick-start/example/ingress.yaml
  docs/tutorials/quick-start/example/production-issuer.yaml
  docs/tutorials/quick-start/example/service.yaml
  docs/tutorials/quick-start/example/staging-issuer.yaml
  docs/tutorials/quick-start/index.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XL

#819 Set the certificate as an owner of the secret
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/controller/certificates/sync.go
  pkg/controller/context.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#713 Add cert-manager specific metrics to Prometheus endpoint
  BUILD.bazel
  Gopkg.lock
  cmd/controller/BUILD.bazel
  cmd/controller/app/BUILD.bazel
  cmd/controller/app/controller.go
  cmd/controller/server.go
  cmd/controller/start.go
  pkg/controller/certificates/BUILD.bazel
  pkg/controller/certificates/controller.go
  pkg/controller/certificates/sync.go
  pkg/metrics/BUILD.bazel
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  vendor/github.com/prometheus/client_golang/AUTHORS.md
  vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1106 fix numbering of steps in quickstart
  docs/tutorials/quick-start/index.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1062 Add Errored type and mark orders as errored when creating fails
  pkg/acme/util.go
  pkg/apis/certmanager/v1alpha1/types_order.go
  pkg/controller/acmeorders/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1061 Use Events API to report validation errors with ingress-shim
  pkg/controller/ingress-shim/BUILD.bazel
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
  test/unit/gen/issuer.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1115 Fix potential race in e2e duration checking
  test/e2e/suite/issuers/ca/certificate.go
  test/e2e/suite/issuers/selfsigned/certificate.go
  test/e2e/suite/issuers/vault/certificate/approle.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1114 Make Certificate Ready condition behaviour consistent between all issuer types
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/controller/acmeorders/checks.go
  pkg/controller/acmeorders/controller.go
  pkg/controller/acmeorders/sync.go
  pkg/controller/certificates/checks.go
  pkg/controller/certificates/controller.go
  pkg/controller/certificates/sync.go
  pkg/issuer/acme/issue.go
  pkg/issuer/ca/issue.go
  pkg/issuer/selfsigned/BUILD.bazel
  pkg/issuer/selfsigned/issue.go
  pkg/issuer/vault/BUILD.bazel
  pkg/issuer/vault/issue.go
  pkg/util/kube/pki.go
  pkg/util/pki/csr.go
Labels: approved, area/provider-acme, area/provider-ca, area/provider-vault, dco-signoff: yes, lgtm, release-note, size/XL

#1119 Remove requeue option and fix small race in controllers
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmeorders/controller.go
  pkg/controller/certificates/controller.go
  pkg/controller/certificates/sync.go
  pkg/controller/clusterissuers/controller.go
  pkg/controller/clusterissuers/sync.go
  pkg/controller/ingress-shim/controller.go
  pkg/controller/issuers/controller.go
  pkg/controller/issuers/sync.go
  pkg/issuer/acme/issue_test.go
  pkg/issuer/acme/setup.go
  pkg/issuer/ca/issue_test.go
  pkg/issuer/ca/setup.go
  pkg/issuer/issuer.go
  pkg/issuer/selfsigned/setup.go
  pkg/issuer/vault/setup.go
Labels: approved, area/provider-acme, area/provider-ca, area/provider-vault, dco-signoff: yes, lgtm, release-note-none, size/L

#1116 CleanUp ACME challenges after issuing and on delete using finalizer
  pkg/apis/certmanager/v1alpha1/const.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmechallenges/sync_test.go
  pkg/controller/acmeorders/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1121 Don't update Certificate status condition upon issuance
  pkg/controller/certificates/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1125 Switch issuer.Issue to return a pointer and fix up setting secret fields
  pkg/controller/certificates/sync.go
  pkg/issuer/acme/issue.go
  pkg/issuer/acme/issue_test.go
  pkg/issuer/ca/issue.go
  pkg/issuer/ca/issue_test.go
  pkg/issuer/issuer.go
  pkg/issuer/selfsigned/issue.go
  pkg/issuer/vault/issue.go
Labels: approved, area/provider-acme, area/provider-ca, area/provider-vault, dco-signoff: yes, lgtm, release-note-none, size/L

#1111 Retry dns queries with TCP if UDP has an i/o timeout
  pkg/issuer/acme/dns/util/wait.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/XS
