Repository cert-manager/cert-manager, pull requests merged in 2018-03, with the labels that each got.

#361 Use Google's DNS IPs instead of domain
  pkg/issuer/acme/dns/util/wait.go
Labels: approved, lgtm, release-note-none, size/XS

#359 Document the minimum necessary permissions for using cert-manager with Route53
  docs/api-types/issuer/spec.md
Labels: approved, lgtm, needs-ok-to-test, release-note, retest-not-required-docs-only, size/S

#372 Verify helm chart version is bumped when a chart is changed
  Makefile
  hack/verify-chart-version.sh
Labels: approved, lgtm, release-note-none, retest-not-required, size/M

#384 Add missing apiVersion to Issuer sample docs
  docs/api-types/issuer/README.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only

#385 Fix .gitlab-ci.yml build
  .gitlab-ci.yml
Labels: approved, lgtm, release-note-none, retest-not-required

#350 Helm Chart: Add support for affinity and tolerations
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/rbac/clusterissuer-crd.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/issuer-crd.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
  docs/deploy/without-rbac/clusterissuer-crd.yaml
  docs/deploy/without-rbac/deployment.yaml
  docs/deploy/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note, retest-not-required, size/M

#381 docs/devel: add 'deploy to minikube' docs
  docs/devel/README.md
  docs/examples/acme-cert.yaml
Labels: approved, lgtm, release-note-none, size/M

#351 Fix various typos in spelling of Certificate
  docs/user-guides/acme-dns-validation.md
  docs/user-guides/acme-http-validation.md
  docs/user-guides/ca-based-issuer.md
  pkg/controller/certificates/sync.go
Labels: approved, lgtm, release-note-none, size/S

#382 Document common ingressShim.extraArgs use case in chart
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/values.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/rbac/clusterissuer-crd.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/issuer-crd.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
  docs/deploy/without-rbac/clusterissuer-crd.yaml
  docs/deploy/without-rbac/deployment.yaml
  docs/deploy/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note-none, size/M

#376 Clarify ClusterIssuer resource namespace
  docs/user-guides/migrating-from-kube-lego.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#391 Trim aws credentials for acme dns route53 provider
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
Labels: approved, lgtm, release-note, size/L

#386 Reconfigure certs when ingress config changes
  cmd/ingress-shim/controller/sync.go
  cmd/ingress-shim/controller/sync_test.go
Labels: approved, lgtm, release-note, size/L

#396 Fix verify-chart-version script when running more than once
  hack/verify-chart-version.sh
Labels: approved, lgtm, release-note-none, size/XS

#397 make: split 'verify_pr' out
  .travis.yml
  Makefile
  hack/verify-chart-version.sh
Labels: approved, lgtm, release-note-none, size/S

#387 Add podAnnotations
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/rbac/clusterissuer-crd.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/issuer-crd.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
  docs/deploy/without-rbac/clusterissuer-crd.yaml
  docs/deploy/without-rbac/deployment.yaml
  docs/deploy/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note, size/M

#408 Add limits to http validation pod
  pkg/issuer/acme/http/http.go
  test/e2e/framework/util.go
Labels: approved, lgtm, release-note, size/M

#363 Allow non-static AWS credentials for Route 53, gated by "ambient credentials" flags
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  docs/api-types/issuer/spec.md
  docs/examples/acme-issuer.yaml
  docs/examples/cluster-issuer.yaml
  docs/user-guides/ambient-credentials.md
  docs/user-guides/cluster-issuers.md
  pkg/issuer/acme/acme.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
  pkg/issuer/acme/dns/route53/route53.go
  pkg/issuer/acme/dns/route53/route53_integration_test.go
  pkg/issuer/acme/dns/route53/route53_test.go
  pkg/issuer/context.go
Labels: approved, lgtm, release-note, size/L

#416 Delete .travis.yml
  .travis.yml
Labels: approved, lgtm, release-note-none, size/S
