Repository cert-manager/cert-manager, pull requests merged in 2018-06, with the labels that each got.

#609 Fix references to other documentation sections.
  docs/tutorials/acme/migrating-from-kube-lego.rst
Labels: approved, lgtm, release-note-none, size/S

#522 Support for custom dns settings
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note, size/M

#615 Automated cherry pick of #522
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, size/M

#620 Fix links in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#621 Add note about Google Group to readme
  README.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/S

#623 Update labels.yaml
  labels.yaml
Labels: approved, lgtm, release-note-none

#555 Improve logs for CloudDNS service account errors
  pkg/issuer/acme/dns/dns.go
Labels: approved, area/provider-acme, lgtm, release-note-none, size/XS

#627 Automated cherry pick of #609
  docs/tutorials/acme/migrating-from-kube-lego.rst
Labels: approved, lgtm, release-note-none, size/S

#598 issuer/acme/*: log namespaces for resources
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/http/http_test.go
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/service.go
Labels: approved, area/provider-acme, lgtm, release-note-none, size/M

#628 Vault issuer MUST USE the vault 'sign' endpoint
  docs/tutorials/vault/creating-vault-issuers.rst
Labels: approved, lgtm, release-note-none, size/XS

#638 Add Richard Wall to OWNERS file
  OWNERS
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#642 Create common GenerateCSR and GenerateTemplate methods for creating Certificate/CertificateRequest
  pkg/issuer/acme/issue.go
  pkg/issuer/ca/issue.go
  pkg/issuer/vault/issue.go
  pkg/util/pki/csr.go
Labels: approved, lgtm, release-note-none, size/L

#648 Update develop-with-minikube.rst
  docs/devel/develop-with-minikube.rst
Labels: approved, lgtm, release-note-none, size/XS

#582 FindZoneByFqdn fixes from lego
  pkg/issuer/acme/dns/util/wait.go
  pkg/issuer/acme/dns/util/wait_test.go
Labels: approved, area/provider-acme, lgtm, release-note, size/M

#655 Update e2e test ACME email
  test/e2e/certificate/certificate_acme.go
Labels: approved, lgtm, release-note-none, size/XS

#629 Check the acme issuer has the challenge type configured.
  pkg/issuer/acme/prepare.go
Labels: approved, lgtm, release-note-action-required, size/XS

#652 issuer/dns/route53: add myself as owner
  pkg/issuer/acme/dns/route53/OWNERS
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#572 Update the 'fullname' template to match helm 2.8.2
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/_helpers.tpl
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#592 Add DOCKER_BUILD_FLAGS environment variable
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#662 issuers: Skip triggering API update if status has not changed
  pkg/controller/clusterissuers/sync.go
  pkg/controller/issuers/sync.go
Labels: approved, lgtm, release-note, size/S

#674 Don't return invalid/expired orders in shouldAttemptValidation
  pkg/issuer/acme/prepare.go
Labels: approved, lgtm, release-note, size/XS

#676 Automated cherry pick of #628 #655 #662 #674
  docs/tutorials/vault/creating-vault-issuers.rst
  pkg/controller/clusterissuers/sync.go
  pkg/controller/issuers/sync.go
  pkg/issuer/acme/prepare.go
  test/e2e/certificate/certificate_acme.go
Labels: approved, lgtm, release-note-none, size/S

#679 Version bump for v0.3.1
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note-none, size/M

#667 pkg/scheduler: fix minor race; use mocks in scheduler tests
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: approved, lgtm, release-note-none, size/L

#556 charts/cert-manager: add extraEnv
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, lgtm, release-note, size/M

#684 Run dep status as part of CI
  Gopkg.lock
  Makefile
  vendor/golang.org/x/net/publicsuffix/gen.go
  vendor/golang.org/x/net/publicsuffix/list.go
  vendor/golang.org/x/net/publicsuffix/list_test.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/golang.org/x/net/publicsuffix/table_test.go
Labels: approved, lgtm, release-note-none, size/XXL

#685 Update dep verify step to also ensure vendor is up to date
  Gopkg.toml
  Makefile
  hack/update-deps.sh
  hack/verify-deps.sh
  vendor/github.com/hashicorp/go-rootcerts/.travis.yml
  vendor/github.com/hashicorp/go-rootcerts/Makefile
  vendor/github.com/hashicorp/go-rootcerts/README.md
  vendor/github.com/hashicorp/go-rootcerts/test-fixtures/capath-with-symlinks/securetrust.pem
  vendor/github.com/hashicorp/go-rootcerts/test-fixtures/capath-with-symlinks/thawte.pem
  vendor/github.com/json-iterator/go/skip_tests/array/skip_test.go
  vendor/github.com/json-iterator/go/skip_tests/object/skip_test.go
  vendor/github.com/json-iterator/go/skip_tests/string/skip_test.go
  vendor/github.com/prometheus/procfs/.travis.yml
  vendor/github.com/prometheus/procfs/CONTRIBUTING.md
  vendor/github.com/prometheus/procfs/MAINTAINERS.md
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/fixtures/26231/exe
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/0
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/1
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/10
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/2
  vendor/github.com/prometheus/procfs/fixtures/26231/fd/3
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/0
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/1
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/2
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/3
  vendor/github.com/prometheus/procfs/fixtures/26232/fd/4
  vendor/github.com/prometheus/procfs/fixtures/self
  vendor/github.com/prometheus/procfs/ttar
Labels: approved, lgtm, release-note-none, size/L

#682 Resource validation as part of controller sync loops
  Gopkg.lock
  pkg/apis/certmanager/validation/certificate.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/apis/certmanager/validation/clusterissuer.go
  pkg/apis/certmanager/validation/issuer.go
  pkg/apis/certmanager/validation/issuer_test.go
  pkg/controller/certificates/sync.go
  pkg/controller/clusterissuers/sync.go
  pkg/controller/clusterissuers/sync_test.go
  pkg/controller/issuers/sync.go
  pkg/controller/issuers/sync_test.go
Labels: approved, lgtm, release-note, size/XXL

#686 Update spec.acme.config field when ingress changes
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
Labels: approved, lgtm, release-note, size/L

#689 Install dep during gitlab-ci build
  .gitlab-ci.yml
Labels: release-note-none, size/XS
