Repository cert-manager/cert-manager, pull requests merged in 2018-02, with the labels that each got.

#307 Ensure certificate is valid for given domains during e2e tests
  test/e2e/certificate/certificate_acme.go
  test/e2e/certificate/certificate_ca.go
  test/e2e/framework/certificate.go
Labels: approved, lgtm, release-note-none, size/L

#317 Bundle the CA public key in issued certificate
  pkg/issuer/ca/issue.go
Labels: approved, lgtm, release-note, size/XS

#321 Log potential errors while waiting for DNS record propagation
  pkg/issuer/acme/dns/dns.go
Labels: approved, lgtm, release-note-none, size/XS

#326 Install Helm during .gitlab-ci.yml release build
  .gitlab-ci.yml
Labels: approved, lgtm, release-note-none, retest-not-required, size/XS

#325 Check the value of the tls-acme annotation, not just its existence
  cmd/ingress-shim/controller/sync.go
  cmd/ingress-shim/controller/sync_test.go
Labels: approved, lgtm, release-note, size/S

#327 fix: Use ConfigMaps for leaderelection
  cmd/controller/app/controller.go
  cmd/ingress-shim/app.go
  contrib/charts/cert-manager/templates/rbac.yaml
  docs/deploy/rbac/rbac.yaml
Labels: approved, lgtm, release-note-action-required, size/S

#312 Add default shortNames to certificates CRD
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/certificate-crd.yaml
  contrib/charts/cert-manager/values.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
Labels: approved, lgtm, release-note, retest-not-required, size/S

#331 Make existing TLS certificate check emit a Normal event instead of Warning when the existing certificate is invalid
  pkg/controller/certificates/sync.go
Labels: approved, lgtm, release-note, size/XS

#330 Update default deployment namespace to be 'cert-manager'
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/templates/serviceaccount.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/deployment.yaml
  hack/update-deploy-gen.sh
Labels: approved, lgtm, release-note, size/XS

#340 Create a Namespace resource as part of the static manifest bundle
  contrib/charts/cert-manager/templates/00-namespace.yaml
  contrib/charts/cert-manager/values.yaml
  docs/deploy/rbac/00-namespace.yaml
  docs/deploy/without-rbac/00-namespace.yaml
  hack/update-deploy-gen.sh
Labels: approved, lgtm, release-note-none, retest-not-required, size/S

#329 Set default cluster resource namespace to current pod namespace
  contrib/charts/cert-manager/templates/deployment.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/without-rbac/deployment.yaml
  test/e2e/clusterissuer/clusterissuer_ca.go
  test/e2e/e2e.go
Labels: approved, lgtm, release-note-action-required, size/M

#343 Add Endpoints back into the cert-manager RBAC policy
  contrib/charts/cert-manager/templates/rbac.yaml
  docs/deploy/rbac/rbac.yaml
Labels: approved, lgtm, release-note-none, size/S

#346 docs: fix value name that disables rbac
  docs/user-guides/deploying.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#352 Update guides to use official Charts repository
  docs/user-guides/deploying.md
  docs/user-guides/migrating-from-kube-lego.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/S

#356 Remove old deployment manifests. Update RBAC disable advice.
  docs/examples/ca-issuer.yaml
  docs/examples/crd.yaml
  docs/examples/tpr.yaml
  docs/user-guides/deploying.md
Labels: approved, lgtm, release-note-none, size/M
