Repository cert-manager/cert-manager, pull requests merged in 2018-09, with the labels that each got.

#858 [jjo] fix panic from acmedns.go constructor failure
  pkg/issuer/acme/dns/acmedns/acmedns.go
  pkg/issuer/acme/dns/acmedns/acmedns_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#869 added affinity and tolerations
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#875 doc: add minimal ingress-shim example
  docs/reference/ingress-shim.rst
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#878 Rename legacy minikube e2e testing script
  hack/ci/run-e2e-kind.sh
  hack/ci/run-e2e-minikube.sh
  test/fixtures/kind-config-force.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#879 Run dep ensure with dep 0.5 & gofmt with go 1.11
  Gopkg.lock
  pkg/controller/ingress-shim/sync_test.go
  pkg/issuer/vault/issue.go
  test/util/vault/util.go
  third_party/crypto/acme/acme.go
  vendor/cloud.google.com/go/license_test.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
  vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
  vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#881 Bump golang and dep version on gitlab
  .gitlab-ci.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#882 Standardise verify make targets
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#883 Fix acme.privateKeySecretRef validation message
  pkg/apis/certmanager/validation/issuer.go
  pkg/apis/certmanager/validation/issuer_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#884 Fix JUnit e2e test output
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#664 enable clouddns meta auth
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/acme/dns/clouddns/clouddns_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/util_test.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/M

#885 Update version numbers for v0.5.0
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#838 Set Organization in Certificates
  docs/generated/reference/output/reference/api-docs/index.html
  docs/tutorials/ca/creating-ca-issuer.rst
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/certificate_for_issuer.go
  pkg/apis/certmanager/validation/certificate_for_issuer_test.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/util/pki/csr.go
  test/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#886 Chart updates based on helm/charts feedback
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/requirements.lock
  contrib/charts/cert-manager/requirements.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/charts/cert-manager/webhook/Chart.yaml
  contrib/charts/cert-manager/webhook/templates/ca-sync.yaml
  contrib/charts/cert-manager/webhook/values.yaml
  contrib/manifests/cert-manager/with-rbac-webhook.yaml
  contrib/manifests/cert-manager/with-rbac.yaml
  contrib/manifests/cert-manager/without-rbac-webhook.yaml
  contrib/manifests/cert-manager/without-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#889 Add an error check for AzureDNS failure to create a solver.
  pkg/issuer/acme/dns/dns.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#856 Documentation fix for `hostedZoneID` field
  docs/reference/issuers/acme/dns01.rst
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#661 [ACME] Add RFC2136 DNS Provider (2nd attempt)
  docs/generated/reference/output/reference/api-docs/index.html
  docs/generated/reference/output/reference/api-docs/navData.js
  docs/reference/issuers/acme/dns01.rst
  pkg/apis/certmanager/v1alpha1/types_issuer.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/issuer.go
  pkg/apis/certmanager/validation/issuer_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/rfc2136/rfc2136.go
  pkg/issuer/acme/dns/rfc2136/rfc2136_test.go
  pkg/issuer/acme/dns/util_test.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/XL

#891 Relax resource validation for CloudDNS service account credentials
  pkg/apis/certmanager/validation/issuer.go
  pkg/apis/certmanager/validation/issuer_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#905 Add 'make generate' target to run all hack generators
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#917 Fix issues with ingress-shim doc rendering and remove warning
  docs/reference/ingress-shim.rst
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#918 Automated cherry pick of #917
  docs/reference/ingress-shim.rst
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#919 Workaround quay.io not support v2.2 docker image manifests
  .gitlab-ci.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
