Repository cert-manager/cert-manager, pull requests merged in 2018-04, with the labels that each got.

#422 Add a meaningful User-Agent.
  pkg/issuer/acme/acme.go
Labels: approved, lgtm, release-note, size/S

#431 release-0.2: Add empty 'verify_pr' target
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#322 Add ACME DNS-01 provider for Akamai FastDNS
  docs/api-types/issuer/spec.md
  hack/update-codegen.sh
  hack/update-deploy-gen.sh
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/akamai/akamai_test.go
  pkg/issuer/acme/dns/akamai/edgegridauth.go
  pkg/issuer/acme/dns/akamai/edgegridauth_test.go
  pkg/issuer/acme/dns/dns.go
Labels: approved, lgtm, release-note, size/XL

#430 Automated cherry pick of #422
  pkg/issuer/acme/acme.go
Labels: approved, lgtm, size/S

#388 Annotate created secrets with cert information
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/controller/certificates/sync.go
Labels: approved, lgtm, release-note, size/M

#433 Remove --namespace flag
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  cmd/ingress-shim/app.go
  cmd/ingress-shim/options/options.go
  pkg/controller/certificates/controller.go
  pkg/controller/context.go
  pkg/issuer/context.go
Labels: approved, lgtm, release-note, size/M

#432 Plumb a user-agent through pretty much everywhere
  pkg/issuer/acme/acme.go
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/route53/route53.go
  pkg/util/kube/config.go
  pkg/util/useragent_roundtripper.go
  pkg/util/version.go
Labels: approved, lgtm, release-note-none, size/M

#440 add selector, as otherwise it fails on GKE k8s v1.9.x
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/deployment.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/rbac/clusterissuer-crd.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/issuer-crd.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
  docs/deploy/without-rbac/clusterissuer-crd.yaml
  docs/deploy/without-rbac/deployment.yaml
  docs/deploy/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note-none, size/M

#415 Running docker containers as non-root user
  hack/build/dockerfiles/controller/Dockerfile
  hack/build/dockerfiles/ingress-shim/Dockerfile
Labels: approved, lgtm, release-note, size/S

#441 Bump chart version
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/templates/NOTES.txt
  contrib/charts/cert-manager/values.yaml
  docs/deploy/rbac/certificate-crd.yaml
  docs/deploy/rbac/clusterissuer-crd.yaml
  docs/deploy/rbac/deployment.yaml
  docs/deploy/rbac/issuer-crd.yaml
  docs/deploy/rbac/rbac.yaml
  docs/deploy/rbac/serviceaccount.yaml
  docs/deploy/without-rbac/certificate-crd.yaml
  docs/deploy/without-rbac/clusterissuer-crd.yaml
  docs/deploy/without-rbac/deployment.yaml
  docs/deploy/without-rbac/issuer-crd.yaml
  docs/examples/cert-manager.yaml
Labels: approved, lgtm, release-note-none, size/M

#443 Automated cherry pick of #441
  contrib/charts/cert-manager/values.yaml
  docs/examples/cert-manager.yaml
Labels: release-note-none, size/S

#451 Set 5s timeout on helm version command
  hack/ci.sh
Labels: approved, lgtm, release-note-none, size/XS

#452 Automated cherry pick of #451
  hack/ci.sh
Labels: approved, lgtm, release-note-none, size/XS

#450 Update release-0.2 branch with sphinx docs
  README.md
  docs/.gitignore
  docs/Makefile
  docs/README.md
  docs/_static/css/style.css
  docs/api-types/certificate/README.md
  docs/api-types/issuer/README.md
  docs/api-types/issuer/spec.md
  docs/conf.py
  docs/devel/README.md
  docs/devel/develop-with-minikube.rst
  docs/devel/index.rst
  docs/examples/acme-cert.yaml
  docs/examples/acme-issuer.yaml
  docs/examples/ca-cert.yaml
  docs/examples/ca-issuer.yaml
  docs/examples/cert-manager.yaml
  docs/examples/cluster-issuer.yaml
  docs/examples/crd.yaml
  docs/examples/tpr.yaml
  docs/getting-started/1-configuring-helm.rst
  docs/getting-started/2-installing.rst
  docs/getting-started/3-configuring-first-issuer.rst
  docs/getting-started/index.rst
  docs/images/high-level-overview.png
  docs/index.rst
  docs/make.bat
  docs/reference/certificates.rst
  docs/reference/certificates/issuer-specific-config/acme.rst
  docs/reference/clusterissuers.rst
  docs/reference/index.rst
  docs/reference/ingress-shim.rst
  docs/reference/issuers.rst
  docs/reference/issuers/acme/dns01.rst
  docs/reference/issuers/acme/http01.rst
  docs/reference/issuers/acme/index.rst
  docs/reference/issuers/ca/index.rst
  docs/requirements.txt
  docs/tutorials/acme/dns-validation.rst
  docs/tutorials/acme/http-validation.rst
  docs/tutorials/acme/index.rst
  docs/tutorials/acme/migrating-from-kube-lego.rst
  docs/tutorials/acme/securing-nginx-ingress-with-letsencrypt.rst
  docs/tutorials/ca/creating-ca-issuer.rst
  docs/tutorials/ca/index.rst
  docs/tutorials/index.rst
  docs/user-guides/README.md
  docs/user-guides/acme-dns-validation.md
  docs/user-guides/acme-http-validation.md
  docs/user-guides/ca-based-issuer.md
  docs/user-guides/cluster-issuers.md
  docs/user-guides/helm.md
Labels: approved, lgtm, release-note-none, size/XXL

#455 Fix rst syntax error in ingress-shim.rst
  docs/reference/ingress-shim.rst
Labels: lgtm, release-note-none, retest-not-required-docs-only, size/XS

#459 Absorb HTTP client errors in acme http self check
  pkg/issuer/acme/http/http.go
Labels: approved, area/provider-acme, lgtm, release-note-none, size/XS

#461 acme: stop polling authz on 4xx client errors
  third_party/crypto/acme/acme.go
  third_party/crypto/acme/acme_test.go
Labels: approved, area/provider-acme, lgtm, release-note-none, size/M

#460 String replace ACMEv1 endpoints with v2 in docs
  docs/reference/issuers.rst
  docs/reference/issuers/acme/dns01.rst
  docs/reference/issuers/acme/http01.rst
  docs/tutorials/acme/dns-validation.rst
  docs/tutorials/acme/http-validation.rst
  docs/tutorials/acme/migrating-from-kube-lego.rst
Labels: approved, lgtm, release-note-none, size/S

#463 Fix up self check failure error message
  pkg/issuer/acme/prepare.go
Labels: approved, lgtm, release-note-none, size/XS

#464 Update some docs examples for acmev2
  docs/tutorials/acme/dns-validation.rst
  docs/tutorials/acme/http-validation.rst
  docs/tutorials/acme/migrating-from-kube-lego.rst
Labels: approved, lgtm, release-note-none, size/M

#465 Delete old/unused test files. Merge wait-minikube.sh into ci.sh.
  contrib/charts/boulder/.helmignore
  contrib/charts/boulder/Chart.yaml
  contrib/charts/boulder/templates/_helpers.tpl
  contrib/charts/boulder/templates/bhsm-deployment.yaml
  contrib/charts/boulder/templates/bhsm-service.yaml
  contrib/charts/boulder/templates/bmysql-deployment.yaml
  contrib/charts/boulder/templates/bmysql-service.yaml
  contrib/charts/boulder/templates/boulder-deployment.yaml
  contrib/charts/boulder/templates/boulder-service.yaml
  contrib/charts/boulder/values.yaml
  hack/ci.sh
  hack/test/setup-boulder.sh
  hack/test/setup-minikube.sh
  hack/test/wait-boulder.sh
  hack/test/wait-minikube.sh
  hack/ubuntu-nsenter/Dockerfile
  hack/ubuntu-nsenter/README.md
  hack/verify-chart-version.sh
Labels: approved, lgtm, release-note-none, size/L

#473 Fix broken link
  docs/reference/ingress-shim.rst
Labels: approved, lgtm, release-note-none, size/XS

#474 Automated cherry pick of #455 #473
  docs/reference/ingress-shim.rst
Labels: approved, lgtm, release-note-none, size/XS

#475 Fix deployment guide link. Fix inline code block.
  docs/reference/ingress-shim.rst
Labels: approved, lgtm, release-note-none

#476 Automated cherry pick of #475
  docs/reference/ingress-shim.rst
Labels: approved, lgtm, release-note-none, size/XS

#479 Bump to kubernetes 1.10.0
  Gopkg.lock
  Gopkg.toml
  vendor/gopkg.in/jarcoal/httpmock.v1/.gitignore
  vendor/gopkg.in/jarcoal/httpmock.v1/.travis.yml
  vendor/gopkg.in/jarcoal/httpmock.v1/LICENSE
  vendor/gopkg.in/jarcoal/httpmock.v1/README.md
  vendor/gopkg.in/jarcoal/httpmock.v1/doc.go
  vendor/gopkg.in/jarcoal/httpmock.v1/env.go
  vendor/gopkg.in/jarcoal/httpmock.v1/env_test.go
  vendor/gopkg.in/jarcoal/httpmock.v1/response.go
  vendor/gopkg.in/jarcoal/httpmock.v1/response_test.go
  vendor/gopkg.in/jarcoal/httpmock.v1/transport.go
  vendor/gopkg.in/jarcoal/httpmock.v1/transport_test.go
  vendor/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
Labels: approved, lgtm, release-note-none, size/XXL

#484 Add back the commit sha in the `org.label-schema.vcs-ref` label.
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#485 Update README.md
  README.md
Labels: approved, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#488 Add Key Encipherment bit to Key Usage extension
  pkg/issuer/ca/issue.go
Labels: approved, lgtm, release-note, size/XS

#477 Sync cert-manager chart with kubernetes/charts
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/manifests/cert-manager/rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/rbac/deployment.yaml
  contrib/manifests/cert-manager/rbac/issuer-crd.yaml
  contrib/manifests/cert-manager/rbac/rbac.yaml
  contrib/manifests/cert-manager/rbac/serviceaccount.yaml
  contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/without-rbac/deployment.yaml
  contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note-none, size/S

#496 release-0.2: Always use AddRateLimited. Adjust exponential backoff base/max.
  pkg/controller/certificates/controller.go
  pkg/controller/clusterissuers/controller.go
  pkg/controller/issuers/controller.go
  pkg/controller/util.go
Labels: approved, lgtm, release-note, size/S

#495 Remove 'latest' docker image tag
  .gitlab-ci.yml
Labels: approved, lgtm, release-note-none, size/XS

#503 Sync helm chart from kubernetes/charts back to release-0.2
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/OWNERS
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/NOTES.txt
  contrib/charts/cert-manager/templates/_helpers.tpl
  contrib/charts/cert-manager/templates/certificate-crd.yaml
  contrib/charts/cert-manager/templates/clusterissuer-crd.yaml
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/templates/issuer-crd.yaml
  contrib/charts/cert-manager/templates/rbac.yaml
  contrib/charts/cert-manager/templates/serviceaccount.yaml
  contrib/charts/cert-manager/values.yaml
Labels: approved, lgtm, release-note-none, size/L

#504 Bump chart and appVersion on master branch
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/rbac/deployment.yaml
  contrib/manifests/cert-manager/rbac/issuer-crd.yaml
  contrib/manifests/cert-manager/rbac/rbac.yaml
  contrib/manifests/cert-manager/rbac/serviceaccount.yaml
  contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/without-rbac/deployment.yaml
  contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note-none, size/M

#513 Fix and extend DNS01 provider e2e tests
  test/e2e/certificate/certificate_acme_dns01.go
  test/util/generate/certificate.go
Labels: approved, area/provider-acme, lgtm, release-note-none, size/M

#512 Require asterisk denoted wildcard in acme solver config for wildcard certificates
  pkg/issuer/acme/prepare.go
  pkg/issuer/acme/prepare_test.go
  test/e2e/certificate/certificate_acme_dns01.go
  third_party/crypto/acme/types.go
Labels: approved, area/provider-acme, lgtm, release-note, size/L

#515 Fix typo
  docs/reference/issuers.rst
Labels: approved, lgtm, release-note-none, size/XS

#514 Only perform one validation per identifier for a single order at a time
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/issuer/acme/prepare.go
  test/e2e/certificate/certificate_acme_dns01.go
Labels: approved, lgtm, release-note, size/M

#517 Increase timeout for wildcard and apex domain e2e test
  test/e2e/certificate/certificate_acme_dns01.go
  test/e2e/framework/certificate.go
Labels: approved, lgtm, release-note-none, size/S

#493 Allow ingressClass to be specified using ingress-shim
  cmd/ingress-shim/controller/sync.go
  cmd/ingress-shim/controller/sync_test.go
  docs/reference/ingress-shim.rst
Labels: approved, area/provider-acme, kind/feature, lgtm, release-note, size/L

#502 Link ingress-shim into main controller binary
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  cmd/controller/start.go
  cmd/ingress-shim/README.md
  cmd/ingress-shim/app.go
  cmd/ingress-shim/main.go
  cmd/ingress-shim/options/options.go
  cmd/ingress-shim/start.go
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/templates/deployment.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/rbac/deployment.yaml
  contrib/manifests/cert-manager/rbac/issuer-crd.yaml
  contrib/manifests/cert-manager/rbac/rbac.yaml
  contrib/manifests/cert-manager/rbac/serviceaccount.yaml
  contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/without-rbac/deployment.yaml
  contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
  docs/reference/ingress-shim.rst
  docs/tutorials/acme/migrating-from-kube-lego.rst
  pkg/controller/context.go
  pkg/controller/ingress-shim/checks.go
  pkg/controller/ingress-shim/controller.go
  pkg/controller/ingress-shim/sync.go
  pkg/controller/ingress-shim/sync_test.go
  test/e2e/e2e.go
  test/fixtures/cert-manager-values.yaml
Labels: approved, lgtm, release-note-action-required, size/XL

#516 Update chart for v0.3.2-alpha.2
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/values.yaml
  contrib/manifests/cert-manager/rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/rbac/deployment.yaml
  contrib/manifests/cert-manager/rbac/issuer-crd.yaml
  contrib/manifests/cert-manager/rbac/rbac.yaml
  contrib/manifests/cert-manager/rbac/serviceaccount.yaml
  contrib/manifests/cert-manager/without-rbac/certificate-crd.yaml
  contrib/manifests/cert-manager/without-rbac/clusterissuer-crd.yaml
  contrib/manifests/cert-manager/without-rbac/deployment.yaml
  contrib/manifests/cert-manager/without-rbac/issuer-crd.yaml
Labels: approved, lgtm, release-note-none, size/M

#518 Update chart for v0.2.5 release
  contrib/charts/cert-manager/Chart.yaml
  contrib/charts/cert-manager/README.md
  contrib/charts/cert-manager/values.yaml
Labels: approved, lgtm, release-note-none, size/S

#519 Update exponential backoff base to 5s and max to 5m
  pkg/controller/certificates/controller.go
Labels: approved, lgtm, release-note, size/XS
