Repository cert-manager/cert-manager, pull requests merged in 2019-01, with the labels that each got.

#1159 Update bazel rules
  WORKSPACE
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#1174 Bump bazel workspace dependencies
  WORKSPACE
  vendor/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example/install/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example2/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example2/install/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/apis/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/scheme/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example/internalversion/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example2/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/internalversion/typed/example2/internalversion/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/scheme/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example/v1/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/clientset/versioned/typed/example2/v1/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/example/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/example2/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/externalversions/internalinterfaces/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/example/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/example/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/example2/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/example2/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/informers/internalversion/internalinterfaces/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/listers/example/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/listers/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/listers/example2/internalversion/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/apiserver/listers/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/apis/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/apis/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/scheme/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example2/v1/fake/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/example/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/example2/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/example2/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/informers/externalversions/internalinterfaces/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/listers/example/v1/BUILD.bazel
  vendor/k8s.io/code-generator/_examples/crd/listers/example2/v1/BUILD.bazel
Labels: dco-signoff: yes, release-note-none, size/XXL

#1172 Save global addon logs as CI artifacts & fixup logging
  test/e2e/BUILD.bazel
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/framework/addon/BUILD.bazel
  test/e2e/framework/addon/certmanager/addon.go
  test/e2e/framework/addon/chart/addon.go
  test/e2e/framework/addon/globals.go
  test/e2e/framework/addon/nginxingress/nginx.go
  test/e2e/framework/addon/pebble/pebble.go
  test/e2e/framework/addon/vault/vault.go
  test/e2e/framework/framework.go
  test/e2e/suite/issuers/acme/BUILD.bazel
  test/e2e/suite/issuers/acme/certificate/BUILD.bazel
  test/e2e/suite/issuers/acme/certificate/dns01.go
  test/e2e/suite/issuers/acme/certificate/http01.go
  test/e2e/suite/issuers/acme/issuer.go
  test/e2e/suite/issuers/ca/BUILD.bazel
  test/e2e/suite/issuers/ca/certificate.go
  test/e2e/suite/issuers/ca/clusterissuer.go
  test/e2e/suite/issuers/ca/issuer.go
  test/e2e/suite/issuers/selfsigned/BUILD.bazel
  test/e2e/suite/issuers/selfsigned/certificate.go
  test/e2e/suite/issuers/vault/BUILD.bazel
  test/e2e/suite/issuers/vault/certificate/BUILD.bazel
  test/e2e/suite/issuers/vault/certificate/approle.go
  test/e2e/suite/issuers/vault/certificate/approle_custom_mount.go
  test/e2e/suite/issuers/vault/issuer.go
  test/e2e/util/BUILD.bazel
  test/e2e/util/util.go
  test/fixtures/cert-manager-values.yaml
  test/util/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1180 Bump versions for 0.6.0-alpha.0
  deploy/chart/Chart.yaml
  deploy/chart/README.md
  deploy/chart/requirements.lock
  deploy/chart/requirements.yaml
  deploy/chart/values.yaml
  deploy/chart/webhook/Chart.yaml
  deploy/chart/webhook/values.yaml
  deploy/manifests/cert-manager.yaml
  docs/getting-started/2-installing.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1179 Add DOCKER_HOST env var to gitlab build
  .gitlab-ci.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1110 Use GinkgoWriter to print Helm install output
  test/e2e/framework/addon/base/base.go
  test/e2e/framework/addon/chart/BUILD.bazel
  test/e2e/framework/addon/chart/addon.go
  test/e2e/framework/helper/pod_start.go
  test/e2e/framework/log/log.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1183 Remove flakey unit test in dns utils package
  pkg/issuer/acme/dns/util/wait_test.go
Labels: approved, area/testing, dco-signoff: yes, lgtm, release-note-none, size/XS

#1185 remove liveness checks on pebble deployments in e2e tests
  test/e2e/charts/pebble/templates/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1077 feat: Include entire certificate chain if provided
  pkg/controller/certificates/sync.go
  pkg/issuer/ca/issue.go
  pkg/util/kube/pki.go
  pkg/util/pki/csr.go
  pkg/util/pki/parse.go
  test/e2e/suite/issuers/ca/certificate.go
  test/e2e/util/util.go
Labels: approved, area/provider-ca, dco-signoff: yes, lgtm, release-note, size/L

#1192 Add reason when an order/challenge gets marked invalid
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmeorders/sync.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1193 Include CRD and Namespace resources in static deployment manifest file
  deploy/manifests/00-crds.yaml
  deploy/manifests/01-namespace.yaml
  deploy/manifests/cert-manager.yaml
  docs/getting-started/2-installing.rst
  hack/update-deploy-gen.sh
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1194 Add additionalPrinterColumns fields to CustomResourceDefintions
  deploy/manifests/00-crds.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1195 Increase ACME control loop & order creation back-off
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmeorders/controller.go
  pkg/issuer/acme/issue.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/S

#1188 Add --namespace flag
  cmd/controller/app/BUILD.bazel
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmeorders/controller.go
  pkg/controller/certificates/controller.go
  pkg/controller/context.go
  pkg/controller/ingress-shim/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1189 Use pebble built by bazel & pre-pull images during e2e tests
  Makefile
  WORKSPACE
  hack/ci/lib/build_images.sh
  test/e2e/charts/BUILD.bazel
  test/e2e/charts/pebble/BUILD.bazel
  test/e2e/charts/pebble/templates/configmap.yaml
  test/e2e/charts/pebble/templates/deployment.yaml
  test/e2e/charts/pebble/values.yaml
  test/e2e/charts/vault/templates/vault-deployment.yaml
  test/e2e/charts/vault/values.yaml
  test/e2e/framework/addon/nginxingress/nginx.go
  test/e2e/framework/config/tiller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1199 Increase resource requests and limits for cert-manager during e2e tests
  test/fixtures/cert-manager-values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1197 Retain Challenge resources for debugging if an Order enters an invalid state
  pkg/controller/acmeorders/sync.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/XS

#1190 feat(helm chart): add priorityClassName option
  deploy/chart/Chart.yaml
  deploy/chart/README.md
  deploy/chart/requirements.lock
  deploy/chart/requirements.yaml
  deploy/chart/templates/deployment.yaml
  deploy/chart/values.yaml
  deploy/chart/webhook/Chart.yaml
  deploy/chart/webhook/templates/deployment.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#809 Add proposal for Order and Challenge resources
  design/acme-orders-challenges-crd.md
Labels: approved, dco-signoff: yes, kind/design, lgtm, release-note-none, retest-not-required-docs-only, size/L

#1210 only init globals data once
  test/e2e/framework/addon/globals.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS, ¯\_(ツ)_/¯

#1217 Fix issuing a certificate into a pre-existing secret
  pkg/util/kube/pki.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#1218 Add reference docs for Order and Challenge resources
  docs/reference/challenges.rst
  docs/reference/index.rst
  docs/reference/orders.rst
Labels: approved, area/provider-acme, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1224 Update OWNERS files
  OWNERS
  deploy/chart/OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#1222 bump pebble version to get larger timeouts
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1223 Add upgrade notes for v0.6
  docs/admin/upgrading/index.rst
  docs/admin/upgrading/upgrading-0.5-0.6.rst
  docs/getting-started/2-installing.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1221 Disable TLS verification when self-checking
  pkg/issuer/acme/http/http.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/S

#1228 If an Order is already valid, attempt to retrieve existing certificate
  pkg/controller/acmeorders/sync.go
Labels: approved, area/provider-acme, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/M

#1187 Update nginx acme quickstart guide with details on Orders and Challenges
  docs/tutorials/quick-start/index.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1227 Use cached ACME account URL when constructing ACME client
  pkg/acme/acme.go
  third_party/crypto/acme/acme.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/S

#1233 Bump Helm chart version for beta.0
  deploy/chart/Chart.yaml
  deploy/chart/README.md
  deploy/chart/requirements.lock
  deploy/chart/requirements.yaml
  deploy/chart/values.yaml
  deploy/chart/webhook/Chart.yaml
  deploy/chart/webhook/values.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1239 Fix nil map panic when writing to an empty existing Secret
  pkg/controller/certificates/sync.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS

#1235 Move Helm chart to deploy/charts/cert-manager
  deploy/charts/cert-manager/.gitignore
  deploy/charts/cert-manager/.helmignore
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/OWNERS
  deploy/charts/cert-manager/README.md
  deploy/charts/cert-manager/requirements.lock
  deploy/charts/cert-manager/requirements.yaml
  deploy/charts/cert-manager/templates/NOTES.txt
  deploy/charts/cert-manager/templates/_helpers.tpl
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/charts/cert-manager/templates/serviceaccount.yaml
  deploy/charts/cert-manager/values.yaml
  deploy/charts/cert-manager/webhook/.helmignore
  deploy/charts/cert-manager/webhook/Chart.yaml
  deploy/charts/cert-manager/webhook/templates/NOTES.txt
  deploy/charts/cert-manager/webhook/templates/_helpers.tpl
  deploy/charts/cert-manager/webhook/templates/apiservice.yaml
  deploy/charts/cert-manager/webhook/templates/ca-sync.yaml
  deploy/charts/cert-manager/webhook/templates/deployment.yaml
  deploy/charts/cert-manager/webhook/templates/pki.yaml
  deploy/charts/cert-manager/webhook/templates/rbac.yaml
  deploy/charts/cert-manager/webhook/templates/service.yaml
  deploy/charts/cert-manager/webhook/templates/serviceaccount.yaml
  deploy/charts/cert-manager/webhook/templates/validating-webhook.yaml
  deploy/charts/cert-manager/webhook/values.yaml
  hack/update-deploy-gen.sh
  test/e2e/framework/addon/certmanager/addon.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS

#1237 Added securityContext to cert-manager deployment pods in helm chart
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/README.md
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/values.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#1241 Fix testenv for chart testing
  test/chart/.testenv
Labels: approved, area/testing, dco-signoff: yes, lgtm, release-note-none, size/XS

#1245 Set CA sync backoff limit & add verifying installation docs
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/requirements.lock
  deploy/charts/cert-manager/requirements.yaml
  deploy/charts/cert-manager/values.yaml
  deploy/charts/cert-manager/webhook/Chart.yaml
  deploy/charts/cert-manager/webhook/templates/ca-sync.yaml
  deploy/manifests/cert-manager.yaml
  docs/getting-started/2-installing.rst
  docs/getting-started/3-configuring-first-issuer.rst
  test/chart/lib/chartlib.sh
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/L

#1247 Bump version strings for v0.6.0
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/README.md
  deploy/charts/cert-manager/requirements.lock
  deploy/charts/cert-manager/requirements.yaml
  deploy/charts/cert-manager/values.yaml
  deploy/charts/cert-manager/webhook/Chart.yaml
  deploy/charts/cert-manager/webhook/values.yaml
  deploy/manifests/cert-manager-no-webhook.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1248 Bump go to 1.11.4
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1249 Update Chart.yaml in webhook
  deploy/charts/cert-manager/webhook/Chart.yaml
Labels: dco-signoff: yes, release-note-none, size/S

#1244 Surface self-check errors in challenge resource
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmechallenges/sync_test.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/http_test.go
Labels: approved, area/provider-acme, dco-signoff: yes, lgtm, release-note, size/L

#1261 docs: fix a bash snippet in 2-installing.rst
  docs/getting-started/2-installing.rst
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/XS

#1262 Automated cherry pick of #1261
  docs/getting-started/2-installing.rst
Labels: approved, cherry-pick-approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#1259 Add note about disabling validation on existing namespaces to Helm chart
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/README.md
  deploy/manifests/cert-manager-no-webhook.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1266 Respect recursive nameservers flag when finding zone for fqdn
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/akamai/akamai_test.go
  pkg/issuer/acme/dns/azuredns/azuredns.go
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/route53/route53.go
Labels: approved, area/acme, area/acme/dns01, dco-signoff: yes, kind/bug, lgtm, priority/important-soon, release-note, size/S

#1273 Automated cherry pick of #1258 #1266
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/manifests/cert-manager-no-webhook.yaml
  deploy/manifests/cert-manager.yaml
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/akamai/akamai_test.go
  pkg/issuer/acme/dns/azuredns/azuredns.go
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/route53/route53.go
Labels: approved, cherry-pick-approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1276 Use long-lived certificates for the webhook component
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/requirements.lock
  deploy/charts/cert-manager/requirements.yaml
  deploy/charts/cert-manager/webhook/Chart.yaml
  deploy/charts/cert-manager/webhook/templates/pki.yaml
  deploy/manifests/cert-manager-no-webhook.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, area/deploy, dco-signoff: yes, kind/bug, lgtm, release-note, size/M, ¯\_(ツ)_/¯

#1291 Automated cherry pick of #1288
  docs/getting-started/troubleshooting.rst
  docs/getting-started/webhook.rst
Labels: approved, cherry-pick-approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1258 Add RBAC rules for finalizers
  deploy/charts/cert-manager/Chart.yaml
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/manifests/cert-manager-no-webhook.yaml
  deploy/manifests/cert-manager.yaml
Labels: approved, area/deploy, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#1191 Adds key parser for PKCS#8 encoded private keys.
  pkg/util/pki/generate.go
  pkg/util/pki/parse.go
  pkg/util/pki/parse_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#1128 Add IP Address in CSR
  .gitignore
  docs/generated/reference/output/reference/api-docs/index.html
  pkg/apis/certmanager/v1alpha1/types.go
  pkg/apis/certmanager/v1alpha1/types_certificate.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/validation/certificate.go
  pkg/apis/certmanager/validation/certificate_for_issuer.go
  pkg/apis/certmanager/validation/certificate_for_issuer_test.go
  pkg/apis/certmanager/validation/certificate_test.go
  pkg/controller/certificates/sync.go
  pkg/issuer/acme/issue_test.go
  pkg/issuer/vault/issue.go
  pkg/util/pki/csr.go
Labels: approved, area/acme, area/api, area/vault, dco-signoff: yes, kind/documentation, lgtm, release-note, size/L
