Repository cert-manager/cert-manager, pull requests merged in 2020-09, with the labels that each got.

#3232 Fix invalid DNS-1123 on ACME computed names
  pkg/api/util/names.go
  pkg/api/util/names_test.go
  pkg/controller/acmeorders/BUILD.bazel
  pkg/controller/acmeorders/util.go
  pkg/controller/certificaterequests/acme/acme.go
  pkg/controller/certificates/internal/test/test.go
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/controller/certificates/requestmanager/util_test.go
  test/e2e/framework/helper/certificates.go
Labels: approved, area/acme, area/testing, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#3240 Remove pre-1.0 stability warning
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/S

#3242 Cast conversion request in the correct API group
  pkg/webhook/server/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#3254 Revert "Refactor the cainjector to only have 1 leader election"
  cmd/cainjector/app/start.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/M

#3249 pkg/util/pki: fix dropped errors
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#3252 Use separate methods for each ConversionReview type
  pkg/webhook/handlers/BUILD.bazel
  pkg/webhook/handlers/conversion.go
  pkg/webhook/handlers/conversion_test.go
  pkg/webhook/handlers/interfaces.go
  pkg/webhook/server/BUILD.bazel
  pkg/webhook/server/server.go
  pkg/webhook/server/server_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3248 Remove extra space
  pkg/controller/controller.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3268 Add closing quotes
  design/20200326.extensible-certificate-controller.md
Labels: approved, dco-signoff: yes, kind/design, lgtm, ok-to-test, release-note-none, size/XS

#3271 Grant Richard Wall (@wallrj) approver and reviewer permissions
  OWNERS
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3269 Add missing quote to help
  cmd/ctl/pkg/renew/renew.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3280 Keep README.md up to date
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#3262 Only encode EKUs if there are EKUs to be encoded
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#3275 Load cainjector controllers independently
  cmd/cainjector/app/BUILD.bazel
  cmd/cainjector/app/start.go
  cmd/cainjector/main.go
  go.mod
  pkg/controller/cainjector/BUILD.bazel
  pkg/controller/cainjector/controller.go
  pkg/controller/cainjector/indexers.go
  pkg/controller/cainjector/setup.go
  pkg/controller/cainjector/sources.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/L

#3296 Add myself to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3279 Fix double "signing" KU validation
  pkg/internal/apis/certmanager/validation/BUILD.bazel
  pkg/internal/apis/certmanager/validation/certificaterequest.go
  pkg/internal/apis/certmanager/validation/certificaterequest_test.go
  pkg/util/pki/csr_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#3308 Update Helm to 3.3.4
  hack/bin/deps.bzl
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3320 Add _artifacts/ to the .gitignore
  .gitignore
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3316 Bump dependencies
  LICENSES
  go.mod
  go.sum
  hack/build/repos.bzl
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#3321 Implement ACME backoff in the correct place + improve logic
  pkg/acme/BUILD.bazel
  pkg/acme/accounts/BUILD.bazel
  pkg/acme/accounts/client.go
  pkg/acme/client/BUILD.bazel
  pkg/acme/client/interfaces.go
  pkg/acme/util/BUILD.bazel
  pkg/acme/util/util.go
Labels: approved, area/acme, dco-signoff: yes, kind/bug, lgtm, release-note, size/L

#3326 typo of registry in values.yaml
  deploy/charts/cert-manager/values.yaml
Labels: approved, area/deploy, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3330 Added acme resources to clusterroles
  deploy/charts/cert-manager/templates/rbac.yaml
Labels: approved, area/deploy, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/XS

#3328 Remove the Venafi e2e skip
  devel/ci-run-e2e.sh
  test/e2e/suite/conformance/certificates/featureset.go
  test/e2e/suite/conformance/certificates/suite.go
  test/e2e/suite/conformance/certificates/venafi/BUILD.bazel
  test/e2e/suite/conformance/certificates/venafi/venafi.go
  test/e2e/suite/issuers/venafi/tpp/certificate.go
Labels: approved, area/testing, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/L
