Repository cert-manager/cert-manager, pull requests merged in 2021-01, with the labels that each got.

#3556 Fix verify-codegen.sh to ignore Copyright lines
  hack/verify-codegen.sh
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3552 Minor log message clarification
  pkg/controller/cainjector/sources.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#3533 Venafi Issuer now sets the CA.crt field of the Secret
  pkg/controller/certificaterequests/venafi/venafi.go
  pkg/controller/certificaterequests/venafi/venafi_test.go
  pkg/issuer/venafi/client/request.go
  test/e2e/framework/helper/featureset/featureset.go
  test/e2e/framework/helper/validate.go
  test/e2e/framework/helper/validations/BUILD.bazel
  test/e2e/framework/helper/validations/certificates.go
  test/e2e/suite/conformance/certificates/acme/acme.go
  test/e2e/suite/issuers/acme/certificate/BUILD.bazel
  test/e2e/suite/issuers/acme/certificate/dns01.go
  test/e2e/suite/issuers/acme/certificate/http01.go
  test/e2e/suite/issuers/acme/certificate/notafter.go
Labels: approved, area/testing, dco-signoff: yes, kind/feature, lgtm, release-note, size/L

#3593 The development meetings are now hosted on Google Meet
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#3514 E2e tests for external issuers
  devel/BUILD.bazel
  devel/addon/sample-external-issuer/BUILD.bazel
  devel/addon/sample-external-issuer/install.sh
  devel/bin/kustomize
  devel/lib/lib.sh
  devel/setup-e2e-deps.sh
  hack/bin/BUILD.bazel
  hack/bin/deps.bzl
  test/e2e/images.bzl
  test/e2e/suite/conformance/BUILD.bazel
  test/e2e/suite/conformance/certificates/BUILD.bazel
  test/e2e/suite/conformance/certificates/external/BUILD.bazel
  test/e2e/suite/conformance/certificates/external/external.go
  test/e2e/suite/conformance/import.go
Labels: approved, area/testing, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/L

#3583 Add CRD categories
  deploy/crds/crd-certificaterequests.yaml
  deploy/crds/crd-certificates.yaml
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  deploy/crds/crd-orders.yaml
Labels: approved, area/deploy, dco-signoff: yes, kind/feature, lgtm, release-note, size/S

#3604 Passes a singe context with cancel func to all the kubectl plugin com…
  cmd/cainjector/BUILD.bazel
  cmd/cainjector/main.go
  cmd/ctl/BUILD.bazel
  cmd/ctl/cmd/cmd.go
  cmd/ctl/main.go
  cmd/ctl/pkg/convert/convert.go
  cmd/ctl/pkg/create/certificaterequest/certificaterequest.go
  cmd/ctl/pkg/create/certificaterequest/certificaterequest_test.go
  cmd/ctl/pkg/create/create.go
  cmd/ctl/pkg/inspect/inspect.go
  cmd/ctl/pkg/inspect/secret/secret.go
  cmd/ctl/pkg/renew/renew.go
  cmd/ctl/pkg/renew/renew_test.go
  cmd/ctl/pkg/status/certificate/certificate.go
  cmd/ctl/pkg/status/status.go
  cmd/ctl/pkg/version/version.go
  test/integration/ctl/ctl_create_cr_test.go
  test/integration/ctl/ctl_renew_test.go
  test/integration/ctl/ctl_status_certificate_test.go
Labels: approved, area/testing, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/L

#3532 Make CNAME resolver recursive
  pkg/issuer/acme/dns/util/dns.go
  pkg/issuer/acme/dns/util/wait.go
  pkg/issuer/acme/dns/util/wait_test.go
Labels: approved, area/acme, area/acme/dns01, dco-signoff: yes, kind/feature, lgtm, release-note, size/L
