Repository cert-manager/cert-manager, pull requests merged in 2022-04, with the labels that each got.

#4808 Server Side Apply: Adds support for Challenge controllers to use SSA with Feature Gate
  deploy/charts/cert-manager/templates/rbac.yaml
  internal/BUILD.bazel
  internal/controller/challenges/BUILD.bazel
  internal/controller/challenges/OWNERS
  internal/controller/challenges/apply.go
  internal/controller/challenges/apply_test.go
  pkg/controller/acmechallenges/BUILD.bazel
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmeorders/util.go
  test/integration/BUILD.bazel
  test/integration/challenges/BUILD.bazel
  test/integration/challenges/apply_test.go
Labels: size/L, release-note, approved, lgtm, kind/feature, area/acme, dco-signoff: yes, area/testing, area/deploy

#5010 add cert manager blog details in Users
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, dco-signoff: yes, ok-to-test

#5017 Remove OWNERS from helm chart
  deploy/charts/cert-manager/OWNERS
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, dco-signoff: yes, area/deploy

#5016 explicitly mount service-account-token in deployment
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
  deploy/charts/cert-manager/values.yaml
Labels: release-note, approved, lgtm, size/S, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5024 Fix the error is reported to null when it happens
  pkg/controller/acmechallenges/controller.go
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, ok-to-test

#5033 Bump base images
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5026 Add a unit test for challenges reScheduler
  pkg/controller/acmechallenges/BUILD.bazel
  pkg/controller/acmechallenges/controller_test.go
  test/unit/gen/challenge.go
Labels: size/L, release-note-none, approved, lgtm, kind/feature, area/acme, dco-signoff: yes, area/testing, ok-to-test

#5037 [release-1.7] Bump base images
  build/images.bzl
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, cherry-pick-approved

#5032 Remove pkg/util/coverage
  Makefile
  pkg/util/BUILD.bazel
  pkg/util/coverage/BUILD.bazel
  pkg/util/coverage/coverage.go
  pkg/util/coverage/faketestdeps.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#5055 Fix kind cluster creation with kube 1.19
  make/cluster.sh
  make/config/kind/config.yaml
  make/config/kind/config_etcd_no_fsync.yaml
  make/e2e-setup.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5059 Don't use --force option to install addons with helm
  make/e2e-setup.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5050 trim leading ./ from release archives created by Make
  make/cmctl.mk
  make/manifests.mk
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5065 Update logo dimensions + add note about logo location and name
  README.md
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5057 Bump golang.org/x/crypto to v0.0.0-20220411220226-7b82a4e95df4
  go.mod
  go.sum
  hack/build/repos.bzl
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test

#5070 Always save e2e test logs
  make/e2e-setup.mk
  make/e2e.sh
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5051 Set the challenge cleanup finalizer in the Sync function
  pkg/controller/acmechallenges/BUILD.bazel
  pkg/controller/acmechallenges/controller.go
  pkg/controller/acmechallenges/controller_test.go
  pkg/controller/acmechallenges/finalizer.go
  pkg/controller/acmechallenges/finalizer_test.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmechallenges/sync_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes

#4721 Remove `securityContext.enabled` from helm chart
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/values.yaml
  hack/test-securitycontext-deprecation.sh
Labels: size/L, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test, area/deploy

#5076 Logo work
  logo/logo-small.png
  logo/logo.png
  logo/logo.svg
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test

#5077 Use Apply instead of Update to modify resources in tests
  LICENSES
  go.mod
  go.sum
  hack/build/repos.bzl
  internal/controller/certificaterequests/apply.go
  internal/controller/certificates/apply.go
  internal/controller/challenges/apply.go
  pkg/controller/certificate-shim/sync.go
  test/e2e/suite/approval/BUILD.bazel
  test/e2e/suite/approval/approval.go
  test/e2e/suite/approval/userinfo.go
  test/e2e/suite/certificates/BUILD.bazel
  test/e2e/suite/certificates/additionaloutputformats.go
  test/e2e/suite/certificates/secrettemplate.go
  test/e2e/suite/conformance/certificates/BUILD.bazel
  test/e2e/suite/conformance/certificates/tests.go
  test/e2e/suite/serving/BUILD.bazel
  test/e2e/suite/serving/cainjector.go
  test/integration/acme/BUILD.bazel
  test/integration/acme/orders_controller_test.go
  test/integration/certificates/BUILD.bazel
  test/integration/certificates/issuing_controller_test.go
  test/integration/certificates/metrics_controller_test.go
  test/integration/certificates/revisionmanager_controller_test.go
  test/integration/certificates/trigger_controller_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing
