Repository cert-manager/cert-manager, pull requests merged in 2022-08, with the labels that each got.

#5352 Remove straggling BUILD.bazel file
  test/internal/util/BUILD.bazel
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#5354 add inteon to OWNERS
  OWNERS
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, needs-kind

#5360 Fix `/x/net` and `/x/sys`
  LICENSES
  Makefile
  go.mod
  go.sum
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#5361 Fix containerd / go-restful CVEs
  LICENSES
  go.mod
  go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#5358 Add Trivy scanning make targets
  Makefile
  make/scan.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#5362 Simplify static manifest generation
  hack/concat-yaml.sh
  hack/extractcrd/main.go
  make/manifests.mk
Labels: size/L, release-note-none, approved, lgtm, kind/feature, dco-signoff: yes

#5363 Output junit xml using gotestsum
  hack/prune-junit-xml/prunexml.go
  hack/prune-junit-xml/prunexml_test.go
  make/test.mk
Labels: size/L, release-note-none, approved, lgtm, kind/feature, dco-signoff: yes

#5364 Apply go fmt for go1.19
  deploy/crds/crd-certificaterequests.yaml
  deploy/crds/crd-certificates.yaml
  internal/apis/certmanager/types.go
  internal/apis/certmanager/v1alpha2/types.go
  internal/apis/certmanager/v1alpha3/types.go
  internal/apis/certmanager/v1beta1/types.go
  internal/cainjector/feature/features.go
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/policies/policies.go
  internal/webhook/feature/features.go
  pkg/api/scheme.go
  pkg/api/util/conditions.go
  pkg/apis/certmanager/v1/types.go
  pkg/controller/certificate-shim/gateways/controller.go
  pkg/controller/certificate-shim/helper.go
  pkg/controller/certificate-shim/ingresses/controller.go
  pkg/controller/certificate-shim/sync.go
  pkg/controller/certificates/util.go
  pkg/issuer/acme/dns/acmedns/acmedns.go
  pkg/issuer/acme/dns/akamai/akamai.go
  pkg/issuer/acme/dns/akamai/akamai_test.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/util/pki/parse.go
  pkg/webhook/admission/initializer/interfaces.go
  test/unit/gen/certificate.go
Labels: size/L, release-note-none, approved, lgtm, area/api, kind/documentation, area/acme, dco-signoff: yes, area/testing, area/acme/dns01, area/deploy

#5369 [release-1.8]: Don't verify chart in ci-presubmit
  hack/verify-goimports.sh
  make/ci.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes, cherry-pick-approved

#5366 Ensures CertificateRequests marked as 'InvalidRequest' are properly handled as failures & retried
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/readiness/readiness_controller.go
  test/integration/certificates/generates_new_private_key_per_request_test.go
  test/integration/framework/helpers.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#5377 Flaky test: add random suffix to webhooks in CA Injector e2e tests
  test/e2e/suite/serving/cainjector.go
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, kind/flake

#5368 docs: Correct reference to lease not config map
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5382 Document that pod template spec should be used instead of flags
  cmd/controller/app/options/options.go
  pkg/issuer/acme/http/pod.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5311 added healthcheck to containers port spec
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5402 Adds `ExperimentalCertificateSigningRequestControllers` to CSR e2e tests.
  test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, area/testing, needs-kind

#5376 Upgrade gateway api to v0.5.0
  LICENSES
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  go.mod
  go.sum
  internal/apis/acme/types_issuer.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/types_issuer.go
  internal/apis/acme/v1alpha2/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/zz_generated.deepcopy.go
  internal/apis/acme/v1alpha3/types_issuer.go
  internal/apis/acme/v1alpha3/zz_generated.conversion.go
  internal/apis/acme/v1alpha3/zz_generated.deepcopy.go
  internal/apis/acme/v1beta1/types_issuer.go
  internal/apis/acme/v1beta1/zz_generated.conversion.go
  internal/apis/acme/v1beta1/zz_generated.deepcopy.go
  internal/apis/acme/zz_generated.deepcopy.go
  internal/apis/certmanager/validation/issuer_test.go
  make/config/projectcontour/contour-gateway.yaml
  make/e2e-setup.mk
  make/tools.mk
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/controller/cainjector/setup.go
  pkg/controller/certificate-shim/gateways/controller.go
  pkg/controller/certificate-shim/gateways/controller_test.go
  pkg/controller/certificate-shim/sync.go
  pkg/controller/certificate-shim/sync_test.go
  pkg/controller/context.go
  pkg/controller/test/context_builder.go
  pkg/issuer/acme/http/http.go
  test/e2e/framework/framework.go
  test/e2e/suite/conformance/certificates/acme/acme.go
  test/e2e/util/util.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/XXL, area/acme, dco-signoff: yes, area/testing, area/acme/http01, area/deploy

#5398 Generate Makefile build targets dynamically for tools
  Makefile
  make/README.md
  make/ci.mk
  make/cmctl.mk
  make/e2e-setup.mk
  make/licenses.mk
  make/manifests.mk
  make/release.mk
  make/scan.mk
  make/server.mk
  make/test.mk
  make/tools.mk
  test/internal/apiserver/envs.go
Labels: size/XL, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#5395 Add topologySpreadConstraints to helm chart
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
  deploy/charts/cert-manager/values.yaml
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5401 Add annotations for ServiceMonitor in helm chart
  deploy/charts/cert-manager/templates/servicemonitor.yaml
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5403 move e2e-ci to a script
  make/e2e-ci.sh
  make/test.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5411 Use new tools.mk structure for rclone
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5407 Fix incorrect uses of loop variable
  pkg/controller/controller.go
  test/e2e/suite/issuers/selfsigned/certificaterequest.go
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, ok-to-test, needs-kind

#5410 to help troubleshooting make the helm chart container names unique
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/startupapicheck-job.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
  test/fixtures/upgrade/overlay/cainjector-ops.yaml
  test/fixtures/upgrade/overlay/controller-ops.yaml
  test/fixtures/upgrade/overlay/webhook-ops.yaml
Labels: release-note, approved, lgtm, size/S, dco-signoff: yes, area/testing, ok-to-test, area/deploy, needs-kind

#5413 chore: remove duplicate word in comments
  pkg/metrics/metrics.go
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, area/monitoring, needs-kind
