Repository cert-manager/cert-manager, pull requests merged in 2022-07, with the labels that each got.

#5256 Bump base images to latest available
  build/images.bzl
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5250 Removes support for networking/v1beta1 Ingress
  internal/BUILD.bazel
  internal/ingress/BUILD.bazel
  internal/ingress/convert.go
  internal/ingress/convert_test.go
  internal/ingress/ingress.go
  internal/ingress/ingress_test.go
  internal/ingress/v1.go
  internal/ingress/v1beta1.go
  pkg/controller/acmechallenges/BUILD.bazel
  pkg/controller/acmechallenges/controller.go
  pkg/controller/certificate-shim/BUILD.bazel
  pkg/controller/certificate-shim/ingresses/BUILD.bazel
  pkg/controller/certificate-shim/ingresses/controller.go
  pkg/controller/certificate-shim/sync.go
  pkg/issuer/acme/http/BUILD.bazel
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/ingress.go
Labels: release-note, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/acme/http01

#5252 Port upgrade test to make
  Makefile
  hack/verify-upgrade.sh
  make/ci.mk
  make/git.mk
  make/legacy.mk
  make/test.mk
  make/tools.mk
  test/fixtures/upgrade/overlay/cainjector-ops.yaml
  test/fixtures/upgrade/overlay/controller-ops.yaml
  test/fixtures/upgrade/overlay/webhook-ops.yaml
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#5266 Change all scripts #!/bin/bash -> #!/usr/bin/env bash
  hack/build/print-workspace-status.sh
  hack/update-gofmt.sh
  test/integration/versionchecker/testdata/fetch.sh
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#5264 Kubebuilder Assets darwin/arm64
  make/e2e-setup.mk
  make/tools.mk
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing, area/deploy

#5194 Support secrets for Route53 Access Key IDs
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  internal/apis/acme/types_issuer.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/types_issuer.go
  internal/apis/acme/v1alpha2/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/zz_generated.deepcopy.go
  internal/apis/acme/v1alpha3/types_issuer.go
  internal/apis/acme/v1alpha3/zz_generated.conversion.go
  internal/apis/acme/v1alpha3/zz_generated.deepcopy.go
  internal/apis/acme/v1beta1/types_issuer.go
  internal/apis/acme/v1beta1/zz_generated.conversion.go
  internal/apis/acme/v1beta1/zz_generated.deepcopy.go
  internal/apis/acme/zz_generated.deepcopy.go
  internal/apis/certmanager/validation/issuer.go
  internal/apis/certmanager/validation/issuer_test.go
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/issuer/acme/dns/dns.go
  pkg/issuer/acme/dns/dns_test.go
Labels: size/L, release-note, approved, lgtm, area/api, kind/feature, area/acme, dco-signoff: yes, ok-to-test, area/acme/dns01, area/deploy

#5270 Updates Bazel deps
  hack/build/repos.bzl
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#5272 Use variable for curl, add retries
  make/e2e-setup.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#5273 [release-1.8] Use variable for curl, add retries
  make/e2e-setup.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/feature, size/M, dco-signoff: yes, cherry-pick-approved

#5259 fix: update kyverno version, policy.yaml and securityContexts
  deploy/charts/cert-manager/values.yaml
  devel/addon/kyverno/BUILD.bazel
  devel/addon/kyverno/install.sh
  devel/addon/kyverno/kustomization.yaml
  devel/addon/kyverno/policy.yaml
  make/config/kyverno/kustomization.yaml
  make/config/kyverno/policy.yaml
  make/e2e-setup.mk
  pkg/issuer/acme/http/pod.go
  test/e2e/images.bzl
Labels: release-note, approved, lgtm, kind/bug, size/XXL, area/acme, dco-signoff: yes, area/testing, ok-to-test, area/acme/http01, area/deploy

#5276 Update helm README file
  deploy/charts/cert-manager/README.template.md
Labels: release-note-none, approved, lgtm, kind/cleanup, kind/documentation, size/M, dco-signoff: yes, ok-to-test, area/deploy

#5022 Make: cmctl and kubectl-cert_manager are using two -ldflags, the second -ldflags is cancelling the first one
  Makefile
  make/cmctl.mk
  make/server.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#5285 [release-1.8] make: cmctl and kubectl-cert_manager were using two -ldflags
  Makefile
  make/cmctl.mk
  make/server.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes, cherry-pick-approved

#5288 add missing target for $(BINDIR)
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#5287 Retry update on conflicts during SecretTemplate tests to avoid test flakes
  test/e2e/suite/certificates/BUILD.bazel
  test/e2e/suite/certificates/secrettemplate.go
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, area/testing, kind/flake

#5289 [release-1.9] Add missing target for $(BINDIR)
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes, cherry-pick-approved

#5248 Updates Roadmap
  ROADMAP.md
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#5281 Use order-only prerequisites where possible for tools
  make/README.md
  make/e2e-setup.mk
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5317 E2E test flakes: Additional output formats
  test/e2e/suite/certificates/additionaloutputformats.go
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, kind/flake, flake/test-logic

#5318 E2E test flakes: SecretTemplate
  test/e2e/suite/certificates/secrettemplate.go
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, kind/flake

#5325 E2E test flakes: CertificateRequest Approval
  test/e2e/suite/approval/approval.go
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, kind/flake

#5329 Test Flake: TestManyPasswordLengths: pre-create password test cases outside of concurrent tests
  pkg/controller/certificates/issuing/internal/keystore_test.go
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, kind/flake, flake/test-logic

#5323 [SelfSigned] CertificateSigningRequest: don't mark failed when referenced Secret doesn't exist
  pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go
  pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5339 Remove incorrect Route53 validation on AccessKeyID and SecretAccessKeyID
  internal/apis/certmanager/validation/issuer.go
  internal/apis/certmanager/validation/issuer_test.go
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes
