Repository cert-manager/cert-manager, pull requests merged in 2022-01, with the labels that each got.

#4699 Helm values cleanup
  cmd/cainjector/app/start.go
  cmd/webhook/app/options/options.go
  deploy/charts/cert-manager/values.yaml
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/deploy

#4688 Fixes a bug where a previous failed CertificateRequest was picked up during next issuance
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/issuing/issuing_controller_test.go
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/controller/certificates/requestmanager/requestmanager_controller_test.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#4706 Bump base images
  build/images.bzl
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#4705 Three small goimports fixes against current HEAD
  internal/apis/meta/v1/conversion.go
  pkg/issuer/acme/http/ingress_test.go
  test/e2e/framework/helper/describe.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing, area/acme/http01

#4707 [release-1.6] bump base images
  build/images.bzl
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, cherry-pick-approved

#4703 Pipes in the feature gates from environment to e2e binary
  devel/run-e2e.sh
  test/e2e/e2e_test.go
  test/e2e/framework/config/BUILD.bazel
  test/e2e/framework/config/config.go
  test/e2e/suite/conformance/certificatesigningrequests/BUILD.bazel
  test/e2e/suite/conformance/certificatesigningrequests/suite.go
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#4329 [Helm Chart] Add optional service annotations
  deploy/charts/cert-manager/templates/service.yaml
  deploy/charts/cert-manager/templates/webhook-service.yaml
  deploy/charts/cert-manager/values.yaml
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, ok-to-test, area/deploy

#4690 build cert-manager images for arm on arm
  devel/addon/certmanager/install.sh
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#4710 Add goimports verification and skeleton ci presubmit check
  hack/verify-goimports.sh
  make/Makefile
  make/ci.mk
  make/tools.mk
Labels: release-note, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#4714 Add install for ginkgo which is used for e2e tests
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/feature, dco-signoff: yes

#4715 Match upstream boilerplate verification for files w/ go:build
  hack/verify_boilerplate.py
Labels: release-note-none, approved, lgtm, size/S, kind/feature, dco-signoff: yes

#4711 Add 'cmctl upgrade migrate' tool to assist in v1.7 upgrade
  cmd/ctl/BUILD.bazel
  cmd/ctl/pkg/build/commands/BUILD.bazel
  cmd/ctl/pkg/build/commands/commands.go
  cmd/ctl/pkg/upgrade/BUILD.bazel
  cmd/ctl/pkg/upgrade/migrateapiversion/BUILD.bazel
  cmd/ctl/pkg/upgrade/migrateapiversion/command.go
  cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
  cmd/ctl/pkg/upgrade/upgrade.go
  test/integration/ctl/BUILD.bazel
  test/integration/ctl/migrate/BUILD.bazel
  test/integration/ctl/migrate/ctl_upgrade_migrate_test.go
Labels: release-note, size/XL, approved, lgtm, kind/feature, dco-signoff: yes, area/testing, ok-to-test, area/deploy, area/ctl

#4717 Install ginkgo version from go.mod rather than specifying an explicit version
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/feature, dco-signoff: yes

#4716 Re-organise and extend path loading logic to make it easier to run integration tests using Delve/GoLand
  internal/BUILD.bazel
  internal/apis/acme/install/BUILD.bazel
  internal/apis/acme/install/pruning_test.go
  internal/apis/certmanager/install/BUILD.bazel
  internal/apis/certmanager/install/pruning_test.go
  internal/test/paths/BUILD.bazel
  internal/test/paths/bazel.go
  internal/test/paths/paths.go
  pkg/api/BUILD.bazel
  test/integration/framework/BUILD.bazel
  test/integration/framework/apiserver.go
  test/internal/apiserver/BUILD.bazel
  test/internal/apiserver/envs.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing, ok-to-test

#4670 Re-organise featuregates & add webhook-specific gates
  BUILD.bazel
  cmd/controller/app/BUILD.bazel
  cmd/controller/app/controller.go
  cmd/controller/app/options/BUILD.bazel
  cmd/controller/app/options/options.go
  cmd/webhook/app/BUILD.bazel
  cmd/webhook/app/options/BUILD.bazel
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  devel/addon/certmanager/install.sh
  internal/BUILD.bazel
  internal/apis/config/webhook/fuzzer/fuzzer.go
  internal/apis/config/webhook/types.go
  internal/apis/config/webhook/v1alpha1/zz_generated.conversion.go
  internal/apis/config/webhook/zz_generated.deepcopy.go
  internal/controller/feature/BUILD.bazel
  internal/controller/feature/features.go
  internal/webhook/feature/BUILD.bazel
  internal/webhook/feature/features.go
  pkg/apis/config/webhook/v1alpha1/types.go
  pkg/apis/config/webhook/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/acmechallenges/BUILD.bazel
  pkg/controller/acmechallenges/sync.go
  test/e2e/suite/conformance/certificatesigningrequests/BUILD.bazel
  test/e2e/suite/conformance/certificatesigningrequests/suite.go
Labels: size/L, release-note-none, approved, lgtm, area/api, kind/feature, area/acme, dco-signoff: yes, area/testing, ok-to-test

#4702 Install APIGroup once for multiple DNS providers
  pkg/acme/webhook/apiserver/BUILD.bazel
  pkg/acme/webhook/apiserver/apiserver.go
  pkg/acme/webhook/apiserver/apiserver_test.go
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, ok-to-test

#4628 Order sync cleanup
  pkg/controller/acmeorders/sync.go
  pkg/controller/acmeorders/sync_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes

#4287 Acme http challenge custom dns
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  pkg/controller/context.go
  pkg/issuer/acme/http/BUILD.bazel
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/http_test.go
Labels: size/L, release-note, approved, lgtm, area/api, kind/feature, area/acme, dco-signoff: yes, area/testing, ok-to-test, area/acme/dns01, area/acme/http01, area/deploy

#4697 Don't fail an order that has been finalized, but the status has not been synced to Order CR
  pkg/controller/acmeorders/sync.go
  pkg/controller/acmeorders/sync_test.go
Labels: size/L, release-note, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes

#4728 Move versionchecker tests to test/integration
  pkg/util/versionchecker/BUILD.bazel
  pkg/util/versionchecker/fromcrd.go
  pkg/util/versionchecker/fromservice.go
  pkg/util/versionchecker/versionchecker.go
  test/integration/BUILD.bazel
  test/integration/versionchecker/BUILD.bazel
  test/integration/versionchecker/getpodfromtemplate_test.go
  test/integration/versionchecker/testdata/.gitignore
  test/integration/versionchecker/testdata/BUILD.bazel
  test/integration/versionchecker/testdata/fetch.sh
  test/integration/versionchecker/versionchecker_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#4730 move RFC2136 DNS01 tests to test/integration
  internal/apis/certmanager/validation/util/nameserver.go
  pkg/issuer/acme/dns/rfc2136/BUILD.bazel
  pkg/issuer/acme/dns/rfc2136/rfc2136.go
  test/integration/BUILD.bazel
  test/integration/rfc2136_dns01/BUILD.bazel
  test/integration/rfc2136_dns01/provider_test.go
  test/integration/rfc2136_dns01/rfc2136_test.go
  test/integration/rfc2136_dns01/testdata/config.json
  test/integration/rfc2136_dns01/testdata/rfc2136-tsig-secret.yaml
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing, area/acme/dns01

#4598 Added privateKey additional format option
  deploy/crds/crd-certificates.yaml
  devel/addon/certmanager/install.sh
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/types_certificate.go
  internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go
  internal/apis/certmanager/v1alpha3/types_certificate.go
  internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go
  internal/apis/certmanager/v1beta1/types_certificate.go
  internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go
  internal/apis/certmanager/validation/BUILD.bazel
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/zz_generated.deepcopy.go
  internal/controller/feature/features.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  pkg/controller/certificates/internal/secretsmanager/BUILD.bazel
  pkg/controller/certificates/internal/secretsmanager/secret.go
  pkg/controller/certificates/internal/secretsmanager/secret_test.go
  test/e2e/framework/helper/validation/certificates/certificates.go
  test/e2e/framework/helper/validation/validation.go
  test/e2e/suite/issuers/ca/certificate.go
  test/unit/gen/certificate.go
Labels: release-note, size/XL, approved, lgtm, area/api, kind/feature, dco-signoff: yes, area/testing, ok-to-test, area/deploy

#4745 Makes some minor API naming changes, and clears up some docs around the Certifcate's additional output formats.
  deploy/crds/crd-certificates.yaml
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/types_certificate.go
  internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go
  internal/apis/certmanager/v1alpha3/types_certificate.go
  internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go
  internal/apis/certmanager/v1beta1/types_certificate.go
  internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go
  internal/apis/certmanager/zz_generated.deepcopy.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  pkg/controller/certificates/internal/secretsmanager/secret.go
  pkg/controller/certificates/internal/secretsmanager/secret_test.go
  test/e2e/framework/helper/validation/certificates/certificates.go
  test/e2e/suite/issuers/ca/certificate.go
  test/unit/gen/certificate.go
Labels: size/XL, release-note-none, approved, lgtm, area/api, kind/cleanup, dco-signoff: yes, area/testing, area/deploy

#4752 Don't run AdditionalOutputFormats e2e test if the feature gate is not enabled
  test/e2e/suite/issuers/ca/BUILD.bazel
  test/e2e/suite/issuers/ca/certificate.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#4755 Add a build tag for the e2e test only
  test/e2e/BUILD.bazel
  test/e2e/e2e_test.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#4756 Fix manual invocation of versionchecker testdata fetch
  test/integration/versionchecker/testdata/fetch.sh
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#4719 Reword log messages in the 'cmctl upgrade migrate-api-version' command
  cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, ok-to-test, area/ctl

#4731 add go linters fixes within codebase
  cmd/cainjector/app/start.go
  cmd/ctl/pkg/create/create.go
  cmd/ctl/pkg/factory/validargs.go
  pkg/api/util/kube.go
  pkg/apis/certmanager/v1/types.go
  pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go
  pkg/issuer/acme/dns/clouddns/clouddns.go
  pkg/issuer/vault/vault.go
  pkg/util/pki/kube.go
Labels: release-note-none, approved, lgtm, area/api, kind/documentation, size/M, area/acme, area/vault, dco-signoff: yes, ok-to-test, area/acme/dns01

#4736 Move integration tests to test/integration
  internal/apis/acme/install/BUILD.bazel
  internal/apis/certmanager/install/BUILD.bazel
  test/integration/BUILD.bazel
  test/integration/fuzz/acme/BUILD.bazel
  test/integration/fuzz/acme/pruning_test.go
  test/integration/fuzz/cert-manager/BUILD.bazel
  test/integration/fuzz/cert-manager/pruning_test.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#4638 SecretTemplate reconciliation. SecretManager Apply
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/crds/crd-certificates.yaml
  go.mod
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/v1alpha2/types_certificate.go
  internal/apis/certmanager/v1alpha3/types_certificate.go
  internal/apis/certmanager/v1beta1/types_certificate.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/controller/certificates/internal/secretsmanager/BUILD.bazel
  pkg/controller/certificates/internal/secretsmanager/secret.go
  pkg/controller/certificates/internal/secretsmanager/secret_test.go
  pkg/controller/certificates/issuing/BUILD.bazel
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/issuing/issuing_controller_test.go
  pkg/controller/certificates/issuing/secret_manager.go
  pkg/controller/certificates/issuing/secret_manager_test.go
  pkg/controller/certificates/issuing/temporary.go
  pkg/controller/test/BUILD.bazel
  pkg/controller/test/context_builder.go
  pkg/util/BUILD.bazel
  pkg/util/useragent.go
  pkg/util/useragent_test.go
  test/e2e/suite/BUILD.bazel
  test/e2e/suite/doc.go
  test/e2e/suite/secrettemplate/BUILD.bazel
  test/e2e/suite/secrettemplate/secrettemplate.go
  test/integration/certificates/issuing_controller_test.go
  test/internal/apiserver/BUILD.bazel
  test/internal/apiserver/apiserver.go
  test/unit/coreclients/secrets.go
  test/unit/listers/secret.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/XXL, area/acme, dco-signoff: yes, area/testing, area/deploy

#4753 Add kubebuilder tools in make for integration tests
  make/tools.mk
Labels: release-note-none, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#4751 Remove json tags from internal API types.
  internal/apis/acme/types_issuer.go
  internal/apis/certmanager/types_certificate.go
  test/e2e/framework/helper/validation/certificates/certificates.go
Labels: release-note-none, approved, lgtm, size/S, area/api, kind/cleanup, dco-signoff: yes, area/testing

#4759 Simplify successfully migrated message
  cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test

#4763 Make sure that cmctl x install uses the cert-manager namespace
  cmd/ctl/pkg/install/install.go
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#4764 Upgrade containerd dependency
  go.mod
  go.sum
  hack/build/repos.bzl
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#4766 Specify an --output-base directory for all the gengo tools
  hack/update-codegen.sh
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#4762 Always use the kubernetes.io/ingress.class annotation (#4537)
  internal/ingress/BUILD.bazel
  internal/ingress/convert.go
  internal/ingress/convert_test.go
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, area/acme/http01

#4768 readme: fix broken link
  README.md
Labels: size/XS, release-note, approved, lgtm, kind/documentation, dco-signoff: yes

#4776 Fixes ./devel/cluster/create.sh script
  devel/cluster/create-kind.sh
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#4775 Update PR template to be simpler and mention allowing edits
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#4779 Removes duplicated service annotations from Helm chart
  deploy/charts/cert-manager/templates/service.yaml
  deploy/charts/cert-manager/templates/webhook-service.yaml
  deploy/charts/cert-manager/values.yaml
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/deploy

#4783 Revert "[release-1.5] Use IngressClassName on networking v1 Ingresses"
  pkg/internal/ingress/BUILD.bazel
  pkg/internal/ingress/convert.go
  pkg/internal/ingress/convert_test.go
  pkg/internal/ingress/ingress.go
  pkg/internal/ingress/ingress_test.go
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/ingress_test.go
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, cherry-pick-approved, area/acme/http01

#4746 Certificates controller policies refactor
  BUILD.bazel
  internal/BUILD.bazel
  internal/controller/certificates/BUILD.bazel
  internal/controller/certificates/policies/BUILD.bazel
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/policies/checks_test.go
  internal/controller/certificates/policies/constants.go
  internal/controller/certificates/policies/gatherer.go
  internal/controller/certificates/policies/gatherer_test.go
  internal/controller/certificates/policies/policies.go
  internal/controller/certificates/secrets.go
  internal/controller/certificates/secrets_test.go
  pkg/controller/certificates/BUILD.bazel
  pkg/controller/certificates/issuing/BUILD.bazel
  pkg/controller/certificates/issuing/internal/BUILD.bazel
  pkg/controller/certificates/issuing/internal/keystore.go
  pkg/controller/certificates/issuing/internal/keystore_test.go
  pkg/controller/certificates/issuing/internal/secret.go
  pkg/controller/certificates/issuing/internal/secret_test.go
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/issuing/issuing_controller_test.go
  pkg/controller/certificates/issuing/secret_manager.go
  pkg/controller/certificates/issuing/secret_manager_test.go
  pkg/controller/certificates/issuing/temporary.go
  pkg/controller/certificates/readiness/BUILD.bazel
  pkg/controller/certificates/readiness/readiness_controller.go
  pkg/controller/certificates/readiness/readiness_controller_test.go
  pkg/controller/certificates/trigger/BUILD.bazel
  pkg/controller/certificates/trigger/policies/policies_test.go
  pkg/controller/certificates/trigger/trigger_controller.go
  pkg/controller/certificates/trigger/trigger_controller_test.go
  test/integration/certificates/BUILD.bazel
  test/integration/certificates/trigger_controller_test.go
  test/unit/crypto/BUILD.bazel
  test/unit/crypto/crypto.go
Labels: release-note-none, approved, lgtm, area/api, kind/cleanup, size/XXL, dco-signoff: yes, area/testing, area/deploy
