Repository cert-manager/cert-manager, pull requests merged in 2023-09, with the labels that each got.

#6302 Review Certificate and CertificateRequest API comments
  deploy/crds/crd-certificaterequests.yaml
  deploy/crds/crd-certificates.yaml
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/types_certificaterequest.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/apis/certmanager/v1/types_certificaterequest.go
Labels: size/XL, release-note-none, approved, lgtm, area/api, kind/cleanup, dco-signoff: yes, area/testing, area/deploy

#6318 [release-1.12] Bump to Go 1.20.7
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#6316 Remove old github.com/miekg/dns replace statement
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6317 [release-1.11] Bump to Go 1.19.12
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#6319 Upgrade ctl cert-manager dependency to latest master digest
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6320 Upgrade docker dependencies
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6311 cleanup: Scope mutating webhook to only certificaterequest resources
  deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test, area/deploy

#6333 Fix trivy CVE alert for cyphar/filepath-securejoin
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6337 [release-1.12] Fix trivy CVE alert for cyphar/filepath-securejoin
  LICENSES
  cmd/cainjector/LICENSES
  cmd/controller/LICENSES
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  test/e2e/LICENSES
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, needs-kind

#6332 Upgrade dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  go.mod
  go.sum
  make/base_images.mk
  make/tools.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/XL, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing, area/deploy

#6339 Update cert-manager version imported by cmctl to the latest 'release-1.13' commit
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6349 Add cluster-autoscaler.kubernetes.io/safe-to-evict
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/pod_test.go
Labels: release-note, approved, lgtm, size/S, area/acme, dco-signoff: yes, area/acme/http01, needs-kind

#6354 BUGFIX: CertificateRequest short names must be unique.
  pkg/api/util/names.go
  pkg/api/util/names_test.go
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/controller/certificates/requestmanager/requestmanager_controller_test.go
Labels: size/L, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes

#6357 improvement(helm): fixed empty controller configmap + refactored
  deploy/charts/cert-manager/templates/controller-config.yaml
Labels: release-note, approved, lgtm, size/S, do-not-merge/hold, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6360 improvement(helm): fixed empty webhook configmap + refactored
  deploy/charts/cert-manager/templates/webhook-config.yaml
Labels: release-note, approved, lgtm, size/S, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6366 Fix go-restful dependency "do not use" version
  LICENSES
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6369 Upgrade Go from 1.20.7 to 1.20.8
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes

#6372 [release-1.12] update base images
  make/base_images.mk
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes

#6374 [release-1.13] import latest release 1.13 commit in cmctl
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6328 Add health probe that detects skew between system clock and monotonic go process clock
  deploy/charts/cert-manager/values.yaml
  pkg/healthz/clock_health.go
  pkg/healthz/healthz.go
Labels: release-note, approved, lgtm, kind/feature, size/M, dco-signoff: yes, area/deploy

#6344 Upgrade all dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/tools.mk
  pkg/controller/certificaterequests/venafi/venafi.go
  pkg/controller/certificaterequests/venafi/venafi_test.go
  pkg/controller/certificatesigningrequests/venafi/venafi.go
  pkg/controller/certificatesigningrequests/venafi/venafi_test.go
  pkg/issuer/venafi/client/fake/connector.go
  pkg/issuer/venafi/client/fake/venafi.go
  pkg/issuer/venafi/client/instrumentedvenaficlient.go
  pkg/issuer/venafi/client/request.go
  pkg/issuer/venafi/client/request_test.go
  pkg/issuer/venafi/client/venaficlient.go
  pkg/issuer/venafi/client/venaficlient_test.go
  pkg/webhook/handlers/testdata/apis/testgroup/crds/testgroup.testing.cert-manager.io_testtypes.yaml
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing

#6348 Replace governance documents with link to cert-manager community documents.
  .clomonitor.yml
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  README.md
  SECURITY.md
  SECURITY_CONTACTS.md
  USERS.md
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes
