Repository cert-manager/cert-manager, pull requests merged in 2023-06, with the labels that each got.

#6088 issuer: acme: clouddns: Fix race condition
  pkg/issuer/acme/dns/clouddns/clouddns.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, ok-to-test, area/acme/dns01

#6125 Document what fao stands for in the controller.cert-manager.io/fao label
  design/20221205-memory-management.md
  pkg/apis/certmanager/v1/types.go
Labels: size/XS, release-note-none, approved, lgtm, area/api, kind/design, dco-signoff: yes

#6135 fix function name in comments
  internal/plugin/admission/certificaterequest/approval/certificaterequest_approval.go
  pkg/controller/cainjector/indexers.go
  pkg/controller/util.go
  pkg/util/pki/certificatetemplate.go
  pkg/util/predicate/certificate.go
Labels: release-note-none, approved, lgtm, size/S, needs-ok-to-test, dco-signoff: yes, needs-kind

#6143 Remove service links from http solver pod
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/pod_test.go
Labels: size/XS, release-note, approved, lgtm, area/acme, dco-signoff: yes, ok-to-test, area/acme/http01, needs-kind

#6144 Disable service link in helm chart deployments
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/startupapicheck-job.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6147 BUGFIX: issuer-ref and certificate-name annotations are incorrectly updated on Secrets
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/secrets.go
  internal/controller/certificates/secrets_test.go
  pkg/controller/certificates/issuing/internal/secret.go
  pkg/controller/certificates/issuing/internal/secret_test.go
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/issuing/issuing_controller_test.go
  pkg/controller/certificates/issuing/secret_manager.go
  pkg/controller/certificates/issuing/temporary.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#6094 Attempt to clarify in short the modules proliferation design
  design/20230302.gomod.md
Labels: release-note-none, approved, lgtm, kind/design, kind/documentation, size/M, dco-signoff: yes

#6165 USERS.md: Adds Diagrid organisation
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, dco-signoff: yes

#6166 Add Cluster API to users
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, needs-ok-to-test, dco-signoff: yes

#6153 ip address is missing from error message
  pkg/util/pki/csr.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5003 Implement the DNS-over-HTTPS check
  cmd/controller/app/options/options.go
  cmd/controller/app/options/options_test.go
  pkg/issuer/acme/dns/util/wait.go
  pkg/issuer/acme/dns/util/wait_test.go
Labels: size/L, release-note, approved, lgtm, kind/design, area/acme, dco-signoff: yes, area/testing, ok-to-test, area/acme/dns01, area/acme/http01, area/deploy

#6169 Add Cloudogu logo
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, needs-kind

#6167 Add Metal3 to users
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, needs-ok-to-test, dco-signoff: yes

#6162 Remove old miekg/dns replace statement
  cmd/controller/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6154 BUGFIX: I incidentally removed the feature gate check that enables the UseCertificateRequestBasicConstraints feature
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6170 Fix broken image link in USERS.md
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6172 Add SenseLabs to USERS.md
  USERS.md
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, needs-kind

#6173 Improve documentation of pki.ParseSingleCertificateChain
  pkg/util/pki/parse.go
Labels: release-note-none, approved, lgtm, size/S, kind/documentation, dco-signoff: yes

#6168 Add SecretPublicKeysDiffersFromCurrentCertificateRequest check
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/policies/checks_test.go
  internal/controller/certificates/policies/constants.go
  internal/controller/certificates/policies/policies.go
  pkg/controller/certificates/readiness/readiness_controller_test.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#6171 [Release v1.13.0-alpha.0] Update cmd/cmctl's go.mod to v1.13.0-alpha.0
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: do-not-merge/release-note-label-needed, approved, lgtm, size/M, dco-signoff: yes, area/testing, needs-kind

#6178 Remove the "--tmpdir" flag from mktemp
  hack/check-crds.sh
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, ok-to-test, needs-kind

#6189 Static e2e test build
  make/test.mk
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#6187 Honor KIND_CLUSTER_NAME for e2e-setup & clean
  make/cluster.sh
  make/e2e-setup.mk
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, ok-to-test, needs-kind

#6191 Handle multiple Cloudflare DNS01 challenges for the same FQDN
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, ok-to-test, area/acme/dns01

#6182 BUGFIX: Stricter CertificateRequest CSR webhook validation
  internal/apis/certmanager/validation/certificaterequest.go
  internal/webhook/feature/features.go
  pkg/api/util/kube.go
  pkg/api/util/usages.go
  test/integration/validation/certificaterequest_test.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes, area/testing
