Repository cert-manager/cert-manager, pull requests merged in 2023-05, with the labels that each got.

#5747 BUGFIX: if a LiteralSubject is set, the RequestMatchesSpec function does skip too many checks
  pkg/util/pki/match.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#5814 Add initial support for linux/arm64 as a dev platform
  LICENSES
  cmd/controller/LICENSES
  hack/latest-kubebuilder-shas.sh
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/feature, dco-signoff: yes, ok-to-test

#6013 Bump go + base images
  make/base_images.mk
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#6014 [release-1.11] Bump go and base images to latest
  make/base_images.mk
  make/tools.mk
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5972 Check JKS/PKCS12 truststore in Secrets only if issuer provides the CA
  deploy/crds/crd-certificates.yaml
  internal/controller/certificates/policies/checks.go
  pkg/apis/certmanager/v1/types_certificate.go
Labels: release-note, approved, lgtm, size/S, area/api, kind/bug, dco-signoff: yes, ok-to-test, area/deploy

#6017 Make external DNS webhook tests importable again
  test/acme/fixture.go
  test/acme/options.go
  test/acme/server/doc.go
  test/acme/server/rfc2136.go
  test/acme/server/server.go
  test/acme/suite.go
  test/acme/util.go
  test/apiserver/apiserver.go
  test/apiserver/envs.go
  test/integration/ctl/install_framework/framework.go
  test/integration/framework/apiserver.go
  test/integration/rfc2136_dns01/provider_test.go
  test/integration/rfc2136_dns01/rfc2136_test.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6018 Hide the new healthz server flags
  cmd/controller/app/options/options.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6006 Cache private key hash on issuer status
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  internal/apis/acme/types_issuer.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/types_issuer.go
  internal/apis/acme/v1alpha2/zz_generated.conversion.go
  internal/apis/acme/v1alpha3/types_issuer.go
  internal/apis/acme/v1alpha3/zz_generated.conversion.go
  internal/apis/acme/v1beta1/types_issuer.go
  internal/apis/acme/v1beta1/zz_generated.conversion.go
  pkg/acme/accounts/registry.go
  pkg/acme/accounts/registry_test.go
  pkg/acme/accounts/test/registry.go
  pkg/apis/acme/v1/types_issuer.go
  pkg/issuer/acme/setup.go
  pkg/issuer/acme/setup_test.go
  test/unit/gen/issuer.go
Labels: release-note, approved, lgtm, area/api, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing, ok-to-test, area/deploy

#5991 Server Side Apply: Adds support for CA Injector controller
  cmd/cainjector/app/start.go
  deploy/charts/cert-manager/templates/cainjector-rbac.yaml
  design/20220118.server-side-apply.md
  internal/cainjector/feature/features.go
  make/e2e-setup.mk
  pkg/controller/cainjector/injectables.go
  pkg/controller/cainjector/reconciler.go
  pkg/controller/cainjector/setup.go
  test/e2e/suite/serving/cainjector.go
Labels: size/L, release-note, approved, lgtm, kind/design, dco-signoff: yes, area/testing, area/deploy

#6022 Fix flaky leader election healthz tests
  pkg/healthz/healthz_test.go
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#5828 Add support for json logging format
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/app/app.go
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/acmesolver/main.go
  cmd/cainjector/LICENSES
  cmd/cainjector/app/start.go
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/cainjector/main.go
  cmd/controller/LICENSES
  cmd/controller/app/options/options.go
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/controller/main.go
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/app/options/globalflags.go
  cmd/webhook/app/options/options.go
  cmd/webhook/app/webhook.go
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/acme/webhook/cmd/cmd.go
  pkg/acme/webhook/cmd/server/start.go
  pkg/controller/test/context_builder.go
  pkg/logs/logs.go
  test/e2e/LICENSES
  test/e2e/e2e_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/feature, area/acme, dco-signoff: yes, area/testing, ok-to-test

#6027 Replace deprecated wait.PollImmediateUntil
  cmd/ctl/pkg/check/api/api.go
  cmd/webhook/app/testing/testwebhook.go
  pkg/webhook/authority/authority.go
  pkg/webhook/server/tls/dynamic_source.go
  test/integration/acme/orders_controller_test.go
  test/integration/certificates/issuing_controller_test.go
  test/integration/certificates/metrics_controller_test.go
  test/integration/certificates/revisionmanager_controller_test.go
  test/integration/certificates/trigger_controller_test.go
  test/integration/ctl/ctl_create_cr_test.go
  test/integration/framework/helpers.go
  test/integration/webhook/dynamic_authority_test.go
  test/integration/webhook/dynamic_source_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6036 Fix trivy vulns
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6038 Bump release-1.11 kube libs to latest patch version
  LICENSES
  go.mod
  go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6029 Fix cleanup panic
  test/e2e/suite/issuers/venafi/tpp/certificate.go
  test/e2e/suite/issuers/venafi/tpp/setup.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#6044 Update kubebuilder tools SHAs
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6049 Directly import cert-manager in cmctl
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  make/ci.mk
  make/tools.mk
  test/integration/go.mod
Labels: release-note, approved, lgtm, size/S, kind/feature, dco-signoff: yes, area/testing

#6031 Replace deprecated wait.PollUntil and wait.Poll
  cmd/ctl/pkg/create/certificaterequest/certificaterequest.go
  cmd/ctl/pkg/create/certificatesigningrequest/certificatesigningrequest.go
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/webhook/server/tls/dynamic_source.go
  test/acme/suite.go
  test/acme/util.go
  test/e2e/suite/issuers/acme/issuer.go
  test/integration/certificates/generates_new_private_key_per_request_test.go
  test/integration/ctl/ctl_create_cr_test.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6019 Cleanup CSR util/pki code
  internal/apis/certmanager/validation/certificaterequest.go
  internal/apis/certmanager/validation/certificaterequest_test.go
  pkg/controller/certificaterequests/acme/acme_test.go
  pkg/controller/certificaterequests/ca/ca.go
  pkg/controller/certificaterequests/ca/ca_test.go
  pkg/controller/certificaterequests/selfsigned/selfsigned.go
  pkg/controller/certificaterequests/selfsigned/selfsigned_test.go
  pkg/controller/certificaterequests/sync_test.go
  pkg/controller/certificaterequests/vault/vault_test.go
  pkg/controller/certificaterequests/venafi/venafi_test.go
  pkg/controller/certificates/issuing/internal/keystore_test.go
  pkg/controller/certificates/requestmanager/util_test.go
  pkg/controller/certificatesigningrequests/acme/acme_test.go
  pkg/controller/certificatesigningrequests/ca/ca.go
  pkg/controller/certificatesigningrequests/ca/ca_test.go
  pkg/controller/certificatesigningrequests/selfsigned/selfsigned.go
  pkg/controller/certificatesigningrequests/selfsigned/selfsigned_test.go
  pkg/controller/certificatesigningrequests/venafi/venafi_test.go
  pkg/issuer/venafi/client/request.go
  pkg/util/pki/basicconstraints.go
  pkg/util/pki/certificatetemplate.go
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/keyusage.go
  pkg/util/pki/kube.go
  pkg/util/pki/kube_test.go
  pkg/util/pki/match_test.go
  pkg/util/pki/temporarycertificate.go
  test/integration/certificates/issuing_controller_test.go
  test/integration/certificates/trigger_controller_test.go
  test/unit/crypto/crypto.go
Labels: size/XL, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6059 Bumps c/r to latest commit
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#6061 Bump helm
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6068 Upgrade github.com/docker/distribution v2.8.2+incompatible
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6032 Fix small bugs and make small improvements in ACME code
  make/config/pebble/chart/templates/deployment.yaml
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/pod.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, area/acme, dco-signoff: yes, area/acme/http01

#6070 Upgrade the cert-manager dependency to the 1.12-relaese HEAD commit
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6078 Kubebuilder shas
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6034 apis/acme/v1: ACMEIssuer: set omitempty on optional field
  pkg/apis/acme/v1/types_issuer.go
Labels: size/XS, release-note, approved, lgtm, area/api, dco-signoff: yes, ok-to-test, needs-kind

#6077 Bump k8s.io dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/tools.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing, ok-to-test

#6084 Updates cmctl to point at latest cert-manager
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6085 Disable APF for webhook extension apiserver
  pkg/acme/webhook/cmd/server/start.go
Labels: release-note, approved, lgtm, size/S, kind/cleanup, area/acme, dco-signoff: yes

#6092 [release-1.11] cherry-pick of disabling APF controller in webhook
  pkg/acme/webhook/cmd/server/start.go
Labels: release-note, approved, lgtm, size/S, kind/cleanup, area/acme, dco-signoff: yes

#6093 Fix webhook feature gate
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
  deploy/charts/cert-manager/values.yaml
  internal/cainjector/feature/features.go
  internal/controller/feature/features.go
  internal/webhook/feature/features.go
  make/e2e-setup.mk
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes, area/deploy

#6100 Add a note that folks should not use top level helm featureGates value for webhook feature gates
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/deploy

#6101 Adds a note about usage of featureGates value in Helm chart to release-1.11
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/deploy

#6105 Bumps cert-manager lib in cmctl
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6054 Use Version 3 for *x509.Certificate
  internal/controller/certificates/secrets_test.go
  pkg/controller/certificaterequests/acme/acme_test.go
  pkg/controller/certificaterequests/ca/ca_test.go
  pkg/controller/certificaterequests/venafi/venafi_test.go
  pkg/controller/certificatesigningrequests/ca/ca_test.go
  pkg/util/pki/certificatetemplate.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/generate_test.go
  pkg/util/pki/kube_test.go
  pkg/webhook/authority/authority.go
  pkg/webhook/server/tls/dynamic_source.go
  pkg/webhook/server/tls/file_source_test.go
  test/e2e/util/util.go
  test/framework/addon/vault/vault.go
  test/unit/gen/csr.go
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes, area/testing

#6109 BUGFIX: `cmctl check api --wait 0` should still check the API once
  cmd/ctl/pkg/check/api/api.go
Labels: size/XS, release-note, approved, lgtm, kind/bug, dco-signoff: yes
