Repository cert-manager/cert-manager, pull requests merged in 2023-04, with the labels that each got.

#5909 Migrate tests: higher timeout to lower the number of false-positives
  test/integration/ctl/migrate/ctl_upgrade_migrate_test.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#5910 Fix upstream-tags sort order
  make/git.mk
  make/test.mk
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5843 Design: Go Module Proliferation
  design/20230302.gomod.md
Labels: size/L, release-note-none, approved, lgtm, kind/design, dco-signoff: yes

#5916 Updates cert.status.lastFailureTime description
  deploy/crds/crd-certificates.yaml
  pkg/apis/certmanager/v1/types_certificate.go
Labels: release-note-none, approved, lgtm, size/S, area/api, kind/cleanup, dco-signoff: yes, area/deploy

#5901 Reduce the amount of ACME calls during issuance
  pkg/acme/client/interfaces.go
  pkg/controller/acmeorders/sync.go
  pkg/controller/acmeorders/sync_test.go
  pkg/controller/acmeorders/util.go
  pkg/controller/acmeorders/util_test.go
  test/unit/gen/challenge.go
Labels: size/L, release-note, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#5923 design: fix dead image links
  design/20221205-memory-management.md
Labels: release-note-none, approved, lgtm, kind/cleanup, kind/design, size/M, dco-signoff: yes

#5924 Add a workspace file
  .gitignore
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  go.work
  make/e2e-setup.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#5907 Bump k8s.io dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/tools.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, size/XL, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing, ok-to-test

#5929 Bump distroless base images and kind versions
  make/base_images.mk
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#5928 Remove ioutil
  pkg/webhook/configfile/configfile.go
  test/integration/framework/apiserver.go
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, needs-kind

#5930 [release-1.11] Bump distroless base images and kind versions
  make/base_images.mk
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#3931 Added PodDisruptionBudgets to helm chart
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/cainjector-poddisruptionbudget.yaml
  deploy/charts/cert-manager/templates/poddisruptionbudget.yaml
  deploy/charts/cert-manager/templates/webhook-poddisruptionbudget.yaml
  deploy/charts/cert-manager/values.yaml
Labels: size/L, release-note, approved, lgtm, kind/feature, dco-signoff: yes, ok-to-test, area/deploy

#5934 Fix update-licenses make target
  make/ci.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#5874 Cleanup certificate request approval webhook
  internal/plugin/admission/certificaterequest/approval/certificaterequest_approval.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5932 Use high QPS, Burst, ConcurrentWorkers, ginkgo nodes values for faster e2e tests
  make/e2e-setup.mk
  make/e2e.sh
  make/test.mk
  test/e2e/framework/addon/base/base.go
  test/e2e/framework/framework.go
  test/e2e/suite/certificaterequests/approval/approval.go
  test/e2e/suite/certificaterequests/approval/userinfo.go
Labels: release-note-none, approved, lgtm, size/S, dco-signoff: yes, area/testing, needs-kind

#5935 Remove checked-in go.work, add generation
  .gitignore
  go.work
  make/tools.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5940 Add GCB configuration file for building cert-manager on tag push
  gcb/build_cert_manager.yaml
Labels: release-note-none, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#5943 Add a link to the full release process
  gcb/build_cert_manager.yaml
Labels: size/XS, release-note-none, approved, lgtm, kind/documentation, dco-signoff: yes

#5946 [release-1.10] Autobuild on tag push
  .gitignore
  gcb/build_cert_manager.yaml
Labels: release-note-none, approved, lgtm, kind/feature, size/M, dco-signoff: yes

#5939 Vault test code cleanliness improvements
  test/e2e/framework/addon/vault/proxy.go
  test/e2e/framework/addon/vault/setup.go
  test/e2e/framework/addon/vault/vault.go
  test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go
  test/e2e/suite/issuers/vault/issuer.go
  test/unit/gen/issuer.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#5947 Simplify e2e Helm
  test/e2e/framework/addon/chart/addon.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#5766 Cainjector limit controllers
  cmd/cainjector/app/start.go
  pkg/controller/cainjector/indexers.go
  pkg/controller/cainjector/injectables.go
  pkg/controller/cainjector/reconciler.go
  pkg/controller/cainjector/setup.go
  pkg/controller/cainjector/sources.go
Labels: size/L, release-note, approved, lgtm, kind/feature, dco-signoff: yes

#5949 Fixes status change on privateKey update on acme issuer
  pkg/acme/accounts/registry.go
  pkg/acme/accounts/registry_test.go
  pkg/acme/accounts/test/registry.go
  pkg/issuer/acme/setup.go
  pkg/issuer/acme/setup_test.go
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, ok-to-test

#5965 Upgrade to ko 0.13
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5954 Upgrade to sample-external-issuer v0.3.0
  make/e2e-setup.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5966 Clean up cached Secret resources
  internal/informers/core_filteredsecrets.go
  internal/informers/transfomers.go
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#5968 Use a temporary go.work file when running go-licenses
  make/licenses.mk
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5969 Upgrade to Go 1.20
  cmd/acmesolver/go.mod
  cmd/cainjector/go.mod
  cmd/controller/go.mod
  cmd/ctl/go.mod
  cmd/webhook/go.mod
  go.mod
  make/tools.mk
  test/e2e/go.mod
  test/integration/go.mod
Labels: release-note, approved, lgtm, size/S, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#5967 Validate certificate.spec.secretName is a valid k8s resource name
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, ok-to-test

#5970 Upgrade to go-licenses v1.6.0
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5977 Update kubebuilder tools
  make/tools.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5979 Kind with kube 1.27
  deploy/charts/cert-manager/Chart.template.yaml
  hack/latest-kind-images.sh
  hack/latest-kubebuilder-shas.sh
  make/cluster.sh
  make/e2e-setup.mk
  make/kind_images.sh
  make/tools.mk
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/deploy

#5980 Don't place locally built unversioned images in the cached downloads folder
  make/e2e-setup.mk
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#5981 Upgrade Vault
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/e2e-setup.mk
  test/e2e/LICENSES
  test/e2e/framework/addon/vault/vault.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#5984 Adds kube 1.27 kind image
  hack/latest-kind-images.sh
  make/cluster.sh
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5985 Add a comment that go workspaces are required to use ko make targets
  make/ko.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5976 Cache metadata only for pods and services
  cmd/controller/app/controller.go
  internal/informers/core.go
  internal/informers/core_basic.go
  internal/informers/core_filteredsecrets.go
  pkg/controller/acmechallenges/controller.go
  pkg/controller/context.go
  pkg/controller/test/context_builder.go
  pkg/issuer/acme/http/http.go
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/pod_test.go
  pkg/issuer/acme/http/service.go
  pkg/issuer/acme/http/service_test.go
Labels: release-note, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/acme/http01

#5992 Ensure _bin/scratch exists before attempting to update licenses
  make/licenses.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#5962 Report controller-manager as unhealthy if leader election has failed to renew the lease but process is wedged
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  cmd/controller/go.mod
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/values.yaml
  pkg/healthz/doc.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_test.go
Labels: release-note, size/XL, approved, lgtm, kind/feature, area/acme, dco-signoff: yes, area/testing, area/deploy

#6000 Use boilersuite instead of python
  hack/boilerplate-go.txt
  hack/boilerplate-yaml.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.bzl.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/k8s-codegen.sh
  hack/verify_boilerplate.py
  make/ci.mk
  make/licenses.mk
  make/tools.mk
Labels: size/L, release-note, approved, lgtm, dco-signoff: yes, needs-kind
