Repository cert-manager/cert-manager, pull requests merged in 2023-07, with the labels that each got.

#6176 Reconcile when managed annotations/ labels are out-of-sync
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/policies/checks_test.go
  internal/controller/certificates/policies/constants.go
  internal/controller/certificates/policies/policies.go
  pkg/controller/certificates/issuing/secret_manager_test.go
Labels: release-note, size/XL, approved, lgtm, kind/cleanup, dco-signoff: yes

#6199 Add validation to pki CertificateTemplate functions
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  internal/controller/feature/features.go
  pkg/controller/certificaterequests/acme/acme_test.go
  pkg/controller/certificaterequests/ca/ca.go
  pkg/controller/certificaterequests/selfsigned/selfsigned.go
  pkg/controller/certificatesigningrequests/venafi/venafi_test.go
  pkg/issuer/venafi/client/request.go
  pkg/util/pki/certificatetemplate.go
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/cleanup, kind/feature, dco-signoff: yes, area/testing

#6206 Remove VCert fork dependency replace statement
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  go.mod
  go.sum
  pkg/issuer/venafi/client/request.go
  test/e2e/go.mod
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6208 [release-1.11] remove VCert fork dependency replace statement
  LICENSES
  go.mod
  go.sum
  pkg/issuer/venafi/client/request.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#6207 [release-1.12] remove VCert fork dependency replace statement
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  go.mod
  go.sum
  pkg/issuer/venafi/client/request.go
  test/e2e/go.mod
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6209 service account labels introduce a white line issue
  deploy/charts/cert-manager/templates/serviceaccount.yaml
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, area/deploy, needs-kind

#6225 helm: Update Chart.template.yaml - add apache 2.0 license
  deploy/charts/cert-manager/Chart.template.yaml
Labels: size/XS, release-note, approved, lgtm, needs-ok-to-test, dco-signoff: yes, area/deploy, needs-kind

#6227 Bump k8s.io dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  hack/latest-kind-images.sh
  make/kind_images.sh
  make/tools.mk
  pkg/webhook/handlers/testdata/apis/testgroup/crds/testgroup.testing.cert-manager.io_testtypes.yaml
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, size/XL, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing, ok-to-test

#6087 fix: maxUnavailable pdb configuration cannot be used due to default set minAvailable
  deploy/charts/cert-manager/templates/cainjector-poddisruptionbudget.yaml
  deploy/charts/cert-manager/templates/poddisruptionbudget.yaml
  deploy/charts/cert-manager/templates/webhook-poddisruptionbudget.yaml
  deploy/charts/cert-manager/values.yaml
Labels: release-note, approved, lgtm, size/M, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6234 Use supplied context where possible
  pkg/controller/cainjector/indexers.go
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#6232 [BUGFIX] Incorrect re-assignment of cross-invocation variable
  pkg/controller/cainjector/indexers.go
Labels: size/XS, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#6237 [release-1.12] Use supplied context where possible
  pkg/controller/cainjector/indexers.go
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#6156 chore: When hostNetwork is enabled, dnsPolicy is now set to ClusterFirstWithHostNet.
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6108 Use logging library with json support in cmctl (part 1)
  internal/cmd/util/exit.go
  pkg/logs/logs.go
  pkg/util/cmapichecker/cmapichecker.go
  pkg/util/cmapichecker/cmapichecker_test.go
  pkg/util/versionchecker/versionchecker.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes
