Repository cert-manager/cert-manager, pull requests merged in 2023-02, with the labels that each got.

#5764 Cainjector: only reconcile annotated injectables
  pkg/controller/cainjector/controller.go
  pkg/controller/cainjector/indexers.go
  pkg/controller/cainjector/setup.go
  pkg/controller/cainjector/sources.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/cainjector

#5781 make: the kubebuilder 1.26.0 hash for linux/amd64 changed
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#5776 Vault: add unit tests for the controller-side validation of the Vault Issuer
  pkg/issuer/vault/setup_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/vault, dco-signoff: yes

#5502 The vault issuer can now be given a serviceAccountRef instead of relying on static service account tokens
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  internal/apis/certmanager/types_issuer.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/conversion.go
  internal/apis/certmanager/v1alpha2/types_issuer.go
  internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go
  internal/apis/certmanager/v1alpha3/conversion.go
  internal/apis/certmanager/v1alpha3/types_issuer.go
  internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go
  internal/apis/certmanager/v1beta1/types_issuer.go
  internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go
  internal/apis/certmanager/validation/issuer.go
  internal/apis/certmanager/validation/issuer_test.go
  internal/apis/certmanager/zz_generated.deepcopy.go
  internal/vault/fake/client.go
  internal/vault/vault.go
  internal/vault/vault_test.go
  pkg/apis/certmanager/v1/types_issuer.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  pkg/controller/certificaterequests/vault/vault.go
  pkg/controller/certificaterequests/vault/vault_test.go
  pkg/controller/certificatesigningrequests/vault/vault.go
  pkg/controller/certificatesigningrequests/vault/vault_test.go
  pkg/issuer/vault/setup.go
  pkg/issuer/vault/setup_test.go
  pkg/issuer/vault/vault.go
  test/e2e/framework/addon/chart/addon.go
  test/e2e/framework/addon/vault/setup.go
  test/e2e/suite/issuers/vault/issuer.go
  test/unit/gen/issuer.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/XXL, area/vault, dco-signoff: yes, area/testing, area/deploy

#5793 Bumps base images
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5788 Add 6443/TCP to webhook egress NetworkPolicy
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#5801 Add imagePullSecrets for AMCE http01 solver pod
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  internal/apis/acme/types_issuer.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/types_issuer.go
  internal/apis/acme/v1alpha2/zz_generated.conversion.go
  internal/apis/acme/v1alpha2/zz_generated.deepcopy.go
  internal/apis/acme/v1alpha3/types_issuer.go
  internal/apis/acme/v1alpha3/zz_generated.conversion.go
  internal/apis/acme/v1alpha3/zz_generated.deepcopy.go
  internal/apis/acme/v1beta1/types_issuer.go
  internal/apis/acme/v1beta1/zz_generated.conversion.go
  internal/apis/acme/v1beta1/zz_generated.deepcopy.go
  internal/apis/acme/zz_generated.deepcopy.go
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/pod_test.go
Labels: size/L, release-note, approved, lgtm, area/api, kind/cleanup, kind/feature, area/acme, dco-signoff: yes, ok-to-test, area/acme/http01, area/deploy

#5797 [release-1.10] e2e flakiness: vault addon incorrectly using StdoutPipe
  test/e2e/framework/addon/chart/addon.go
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, kind/flake, cherry-pick-approved

#5795 [release-1.11] e2e flakiness: vault addon incorrectly using StdoutPipe
  test/e2e/framework/addon/chart/addon.go
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, kind/flake, cherry-pick-approved

#5810 Handle uname on linux/arm64
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#5639 Design: reduce cert-manager controller's memory consumption
  design/20221205-memory-management.md
  design/images/20221205-memory-management/createsecrets.png
  design/images/20221205-memory-management/labelsecret.png
  design/images/20221205-memory-management/latestmastersecrets.png
  design/images/20221205-memory-management/mastercertmanager.png
  design/images/20221205-memory-management/masterissuanceterminal.png
  design/images/20221205-memory-management/masterkubeapiserver.png
  design/images/20221205-memory-management/partiallabels.png
  design/images/20221205-memory-management/partialmetadatagrafana.png
  design/images/20221205-memory-management/partialmetadatasecrets.png
  design/images/20221205-memory-management/partialmetadataterminal.png
  design/images/20221205-memory-management/partialnolabels.png
  design/images/20221205-memory-management/partialnolabelscertmanager.png
  design/images/20221205-memory-management/partialnolabelskubeapiserver.png
  design/images/20221205-memory-management/partialonly.png
  design/images/20221205-memory-management/partialonlycertmanager.png
  design/images/20221205-memory-management/partialonlykubeapiserver.png
  design/images/20221205-memory-management/transformfunctionsgrafana.png
  design/images/20221205-memory-management/transformwithlimit.png
Labels: do-not-merge/release-note-label-needed, size/XL, approved, lgtm, kind/design, dco-signoff: yes

#5805 Use jetstack vcert fork to properly reset on TPP error
  LICENSES
  go.mod
  go.sum
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#5813 Bump deps, go and base images
  LICENSES
  go.mod
  go.sum
  make/base_images.mk
  make/tools.mk
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#5815 [release-1.11] Bump deps, go and base images
  LICENSES
  go.mod
  go.sum
  make/base_images.mk
  make/tools.mk
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#5819 [release-1.11] use jetstack vcert fork to properly reset on error for TPP
  LICENSES
  go.mod
  go.sum
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes, area/venafi

#5832 Updates base images
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#5835 Move `cmd/util/` to `internal/cmd/util/`
  cmd/acmesolver/app/app.go
  cmd/acmesolver/main.go
  cmd/cainjector/app/start.go
  cmd/cainjector/main.go
  cmd/controller/app/controller.go
  cmd/controller/app/options/options.go
  cmd/controller/main.go
  cmd/ctl/main.go
  cmd/ctl/pkg/check/api/api.go
  cmd/webhook/app/webhook.go
  cmd/webhook/main.go
  internal/cmd/util/context.go
  internal/cmd/util/defaults.go
  internal/cmd/util/exit.go
  internal/cmd/util/signal.go
  internal/cmd/util/signal_posix.go
  internal/cmd/util/signal_windows.go
  pkg/acme/webhook/cmd/cmd.go
  test/e2e/bin/cloudflare-clean/main.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#5834 Removed unused NewCertManagerWebhookServer function argument
  cmd/webhook/app/testing/testwebhook.go
  cmd/webhook/app/webhook.go
  internal/webhook/webhook.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes
