Repository cert-manager/cert-manager, pull requests merged in 2023-12, with the labels that each got.

#6531 Rename internal API fields to match the field names in the public API
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/v1/conversion.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/conversion.go
  internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha3/conversion.go
  internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  internal/apis/certmanager/v1beta1/conversion.go
  internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
  internal/apis/certmanager/zz_generated.deepcopy.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6535 Refactor GenerateCSR and deprecate the helper functions
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/subject.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6534 Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances
  cmd/cainjector/app/controller.go
  cmd/controller/app/controller.go
  pkg/issuer/acme/http/solver/solver.go
  pkg/webhook/server/server.go
Labels: release-note, approved, lgtm, size/M, area/acme, dco-signoff: yes, area/acme/http01, needs-kind

#6538 [release-1.13] Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances
  cmd/cainjector/app/start.go
  cmd/controller/app/controller.go
  pkg/issuer/acme/http/solver/solver.go
  pkg/webhook/server/server.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, area/acme/http01

#6539 [release-1.12] Mitigate potential Slowloris attacks by setting ReadHeaderTimeout in all http.Server instances
  cmd/cainjector/app/start.go
  cmd/controller/app/controller.go
  pkg/issuer/acme/http/solver/solver.go
  pkg/webhook/server/server.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, area/acme/http01

#6500 feature: added name constraints in certs with isCA enabled
  deploy/crds/crd-certificates.yaml
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/types_certificate.go
  internal/apis/certmanager/v1alpha2/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha2/zz_generated.deepcopy.go
  internal/apis/certmanager/v1alpha3/types_certificate.go
  internal/apis/certmanager/v1alpha3/zz_generated.conversion.go
  internal/apis/certmanager/v1alpha3/zz_generated.deepcopy.go
  internal/apis/certmanager/v1beta1/types_certificate.go
  internal/apis/certmanager/v1beta1/zz_generated.conversion.go
  internal/apis/certmanager/v1beta1/zz_generated.deepcopy.go
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
  internal/apis/certmanager/zz_generated.deepcopy.go
  internal/controller/feature/features.go
  internal/webhook/feature/features.go
  make/e2e-setup.mk
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/apis/certmanager/v1/zz_generated.deepcopy.go
  pkg/controller/certificates/requestmanager/requestmanager_controller.go
  pkg/util/pki/certificatetemplate.go
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/nameconstraints.go
  pkg/util/pki/nameconstraints_test.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/XXL, dco-signoff: yes, ok-to-test, area/deploy

#6544 [release-1.13] Bump to go 1.20.12
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/feature, dco-signoff: yes

#6543 [release-1.12] Bump to go 1.20.12
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/feature, dco-signoff: yes

#6547 [Release v1.12.7] Update cmd/cmctl's go.mod to v1.12.7
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6537 Add the golangci-lint GitHub action
  .github/workflows/golangci-lint.yml
  .golangci.ci.yaml
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#6542 fix: structure of nameconstraint in CSR
  make/e2e-setup.mk
  pkg/util/pki/certificatetemplate.go
  pkg/util/pki/csr.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/nameconstraints.go
  pkg/util/pki/nameconstraints_test.go
Labels: size/XL, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#6555 Fix licenses file
  cmd/webhook/LICENSES
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6556 Add target + installation for golangci-lint
  make/ci.mk
  make/tools.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6552 Add flag and field to customize leaf duration on dynamic certificates
  internal/apis/config/webhook/types.go
  internal/apis/config/webhook/v1alpha1/zz_generated.conversion.go
  internal/webhook/webhook.go
  pkg/apis/config/webhook/v1alpha1/types.go
  pkg/webhook/options/options.go
Labels: release-note, approved, lgtm, size/S, area/api, kind/feature, dco-signoff: yes, ok-to-test

#6551 Fix gosec G601: Implicit memory aliasing of items from a range statement
  .golangci.ci.yaml
  cmd/ctl/pkg/renew/renew.go
  cmd/ctl/pkg/status/certificate/certificate.go
  cmd/ctl/pkg/upgrade/migrateapiversion/migrator.go
  internal/apis/certmanager/validation/certificate_test.go
  internal/apis/certmanager/validation/issuer.go
  pkg/controller/acmeorders/util.go
  pkg/controller/certificate-shim/helper_test.go
  pkg/issuer/vault/setup_test.go
  pkg/util/useragent_test.go
  pkg/webhook/handlers/conversion_test.go
  test/e2e/suite/certificates/duplicatesecretname.go
  test/e2e/suite/issuers/acme/certificate/webhook.go
  test/integration/certificates/generates_new_private_key_per_request_test.go
  test/integration/ctl/ctl_status_certificate_test.go
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, area/vault, dco-signoff: yes, area/testing

#6571 Fix validation webhook error message
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
Labels: release-note, approved, lgtm, size/S, needs-ok-to-test, dco-signoff: yes, needs-kind

#6561 Certificate chain parsing
  pkg/util/pki/parse.go
  pkg/util/pki/parse_certificate_chain.go
  pkg/util/pki/parse_certificate_chain_test.go
  pkg/util/pki/parse_test.go
Labels: size/XL, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6563 Hide deprecated CLI flags
  pkg/logs/logs.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes
