Repository cert-manager/cert-manager, pull requests merged in 2023-10, with the labels that each got.

#6380 BUGFIX[helm]: Fix issue where webhook feature gates were only set if controller feature gates are set (closes #6346)
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
Labels: size/XS, release-note, approved, lgtm, needs-ok-to-test, dco-signoff: yes, area/deploy, needs-kind

#6387 Allow the E2E tests to run on clusters that have not been prepared by the Makefile
  test/e2e/framework/addon/vault/vault.go
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, needs-kind

#6345 Introduce config file for cainjector options
  cmd/cainjector/app/cainjector.go
  cmd/cainjector/app/cainjector_test.go
  cmd/cainjector/app/controller.go
  cmd/cainjector/app/options/options.go
  cmd/cainjector/app/start.go
  cmd/cainjector/go.mod
  cmd/cainjector/main.go
  deploy/charts/cert-manager/templates/cainjector-config.yaml
  deploy/charts/cert-manager/values.yaml
  hack/k8s-codegen.sh
  internal/apis/config/cainjector/doc.go
  internal/apis/config/cainjector/fuzzer/fuzzer.go
  internal/apis/config/cainjector/install/install.go
  internal/apis/config/cainjector/install/roundtrip_test.go
  internal/apis/config/cainjector/register.go
  internal/apis/config/cainjector/scheme/scheme.go
  internal/apis/config/cainjector/types.go
  internal/apis/config/cainjector/v1alpha1/conversion.go
  internal/apis/config/cainjector/v1alpha1/defaults.go
  internal/apis/config/cainjector/v1alpha1/doc.go
  internal/apis/config/cainjector/v1alpha1/register.go
  internal/apis/config/cainjector/v1alpha1/zz_generated.conversion.go
  internal/apis/config/cainjector/v1alpha1/zz_generated.defaults.go
  internal/apis/config/cainjector/validation/validation.go
  internal/apis/config/cainjector/zz_generated.deepcopy.go
  internal/apis/config/controller/types.go
  internal/apis/config/webhook/types.go
  pkg/apis/config/cainjector/doc.go
  pkg/apis/config/cainjector/v1alpha1/doc.go
  pkg/apis/config/cainjector/v1alpha1/register.go
  pkg/apis/config/cainjector/v1alpha1/types.go
  pkg/apis/config/cainjector/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/controller/v1alpha1/types.go
  pkg/apis/config/webhook/v1alpha1/types.go
  pkg/cainjector/configfile/configfile.go
  pkg/cainjector/configfile/configfile_test.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/XXL, dco-signoff: yes, area/deploy

#6053 Make KeyUsage and BasicConstraints Critical extensions in the CSR blob
  pkg/util/pki/basicconstraints.go
  pkg/util/pki/csr_test.go
  pkg/util/pki/keyusage.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#6391 Openshift E2E test compatibility
  make/e2e-setup.mk
  make/test.mk
  test/e2e/framework/addon/vault/vault.go
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6394 [release-1.12] bump base images for release-1.12
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6395 [release-1.13] bump base images to latest
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6396 bump base images
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6398 Venafi issuer: ResetCertificate wasn't working
  pkg/issuer/venafi/client/request.go
Labels: size/XS, release-note, approved, lgtm, dco-signoff: yes, area/venafi, needs-kind

#6410 Bump go to latest to address CVE-2023-39325
  make/base_images.mk
  make/tools.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6414 Fix typo in values.yml
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, area/deploy, needs-kind

#6406 Fix DuplicateSecretName issue
  internal/controller/certificates/certificates.go
  internal/controller/certificates/policies/checks.go
  internal/controller/certificates/policies/checks_test.go
  internal/controller/certificates/policies/constants.go
  internal/controller/certificates/policies/policies.go
  pkg/controller/certificates/trigger/trigger_controller.go
  pkg/controller/certificates/trigger/trigger_controller_test.go
  test/e2e/suite/certificates/duplicatesecretname.go
  test/unit/gen/certificate.go
Labels: release-note, size/XL, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#6426 Rename `webhookConfig` to `controllerConfig`
  pkg/controller/configfile/configfile_test.go
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, needs-kind

#6428 Fix the 'make update-licenses' command on macos
  make/licenses.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6427 Bump golang.org/x/net v0.15.0 => v0.17.0
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, area/testing

#6429 [release-1.12] Licence checker updates
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/cainjector/LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/webhook/LICENSES
  go.mod
  go.sum
  make/licenses.mk
  make/tools.mk
  test/e2e/LICENSES
  test/integration/LICENSES
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6430 [release-1.13] Licence checker updates
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/cainjector/LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/webhook/LICENSES
  go.mod
  go.sum
  make/licenses.mk
  make/tools.mk
  test/e2e/LICENSES
  test/integration/LICENSES
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6435 fix(helm): templating of required value in controller and webhook configmaps
  deploy/charts/cert-manager/templates/cainjector-config.yaml
  deploy/charts/cert-manager/templates/controller-config.yaml
  deploy/charts/cert-manager/templates/webhook-config.yaml
Labels: release-note, approved, lgtm, size/S, dco-signoff: yes, ok-to-test, area/deploy, needs-kind

#6436 [release-1.12] bump otel dependency: fixing CVE alert
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing

#6438 [release-1.13] bump otel dependency: fixing CVE alert
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, dco-signoff: yes, area/testing

#6439 Use sample-external-issuer v0.4.0
  make/e2e-setup.mk
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#6440 Fix image checksum validation and upgrade ingress NGINX to demonstrate the problem
  make/e2e-setup.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6446 [release-1.13] fix HTTP2 CVE alerts
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6447 Fix kindest image digests
  hack/latest-kind-images.sh
  make/e2e-setup.mk
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, needs-kind

#6444 [release-1.12] fix HTTP2 CVE alerts
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6449 Bump gRPC library version to fix CVE alert
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6450 [release-1.12] Update ctl's cert-manager dependency to latest 1.12 commit
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6451 [release-1.13] Update ctl's cert-manager dependency to latest 1.13 commit
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6452 Use latest version of the best-practice Helm values
  make/e2e-setup.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6453 Enable readOnlyRootFilesystem by default
  deploy/charts/cert-manager/values.yaml
  make/config/kyverno/kustomization.yaml
  make/config/kyverno/policy.yaml
Labels: release-note, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/deploy

#6460 feat(helm): allow configuration of cainjector feature gates
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/deploy, needs-kind

#6461 Remove redundant / misleading runAsNonRoot examples from values.yaml
  deploy/charts/cert-manager/values.yaml
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/deploy
