Repository cert-manager/cert-manager, pull requests merged in 2024-03, with the labels that each got.

#6801 Allow `cert-manager.io/allow-direct-injection` in annotations
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
Labels: size/XS, release-note, approved, lgtm, needs-ok-to-test, dco-signoff: yes, needs-kind

#6806 bugfix: include all CA certificates in encoded pkcs12/jks stores
  pkg/controller/certificates/issuing/internal/keystore.go
  pkg/controller/certificates/issuing/internal/keystore_test.go
  pkg/util/pki/parse.go
Labels: size/L, release-note, approved, lgtm, kind/bug, needs-ok-to-test, dco-signoff: yes

#6816 BUGFIX: cainjector leaderelection defaults are missing
  internal/apis/config/cainjector/fuzzer/fuzzer.go
  internal/apis/config/cainjector/v1alpha1/defaults.go
  internal/apis/config/cainjector/v1alpha1/zz_generated.defaults.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#6823 Bump go to 1.21.8
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes

#6813 [release-1.12] bugfix: include all CA certificates in encoded pkcs12/jks stores
  pkg/controller/certificates/issuing/internal/keystore.go
  pkg/controller/certificates/issuing/internal/keystore_test.go
  pkg/util/pki/parse.go
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes

#6827 Bump google.golang.org/protobuf fixing GO-2024-2611
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6828 [release-1.13] upgrade google.golang.org/protobuf, fixing GO-2024-2611
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6830 [release-1.12] upgrade google.golang.org/protobuf fixing GO-2024-2611
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6829 [release-1.14] upgrade google.golang.org/protobuf fixing GO-2024-2611
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/cleanup, size/M, area/acme, dco-signoff: yes, area/testing

#6834 [release-1.14] upgrade Helm to fix CVE-2024-26147
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing

#6831 Bump to latest go version (1.22.1)
  make/tools.mk
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes

#6840 Run ./hack/latest-base-images.sh
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6835 [release-1.13] add trivy exception
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6836 [release-1.12] add trivy exception
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6842 [release-1.14] bump debian12 base images
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6841 [release-1.13] bump debian11 base images
  make/base_images.mk
Labels: release-note, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6832 [release-1.13] BUGFIX: fix datarace due to registering and reading from scheme
  pkg/controller/context.go
Labels: release-note, approved, lgtm, size/S, kind/bug, area/acme, dco-signoff: yes, area/testing

#6833 [release-1.12] BUGFIX: fix datarace due to registering and reading from scheme
  pkg/controller/context.go
Labels: release-note, approved, lgtm, size/S, kind/bug, area/acme, dco-signoff: yes, area/testing

#6844 [release-1.14] Update cmd/ctl's go.mod to v1.14.4
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, needs-kind

#6845 [release-1.13] Update cmd/ctl's go.mod to v1.13.5
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, needs-kind

#6846 [release-1.12] Update cmd/ctl's go.mod to v1.12.9
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, area/testing, needs-kind

#6771 Initialize logger and create root context in main.go
  cmd/acmesolver/app/app.go
  cmd/acmesolver/main.go
  cmd/cainjector/app/cainjector.go
  cmd/cainjector/app/cainjector_test.go
  cmd/cainjector/app/controller.go
  cmd/cainjector/main.go
  cmd/controller/app/controller.go
  cmd/controller/app/start.go
  cmd/controller/app/start_test.go
  cmd/controller/go.sum
  cmd/controller/main.go
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/startupapicheck/main.go
  cmd/startupapicheck/pkg/check/api/api.go
  cmd/startupapicheck/pkg/check/check.go
  cmd/startupapicheck/pkg/factory/factory.go
  cmd/webhook/app/webhook.go
  cmd/webhook/app/webhook_test.go
  cmd/webhook/go.mod
  cmd/webhook/main.go
  internal/cmd/util/context.go
  internal/cmd/util/signal.go
  pkg/acme/webhook/cmd/cmd.go
  pkg/acme/webhook/cmd/server/start.go
  pkg/controller/builder.go
  pkg/controller/test/context_builder.go
  pkg/logs/logs.go
  pkg/webhook/server/server.go
  test/e2e/bin/cloudflare-clean/main.go
  test/e2e/e2e_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#6784 Refactor the webhook dynamic source and add unit tests
  pkg/server/tls/authority/authority.go
  pkg/server/tls/dynamic_source.go
  pkg/server/tls/dynamic_source_test.go
  test/integration/webhook/dynamic_source_test.go
Labels: size/XL, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6839 Add secretTemplate to Certificate resources created by ingress-shim
  pkg/apis/certmanager/v1/types.go
  pkg/controller/certificate-shim/helper.go
  pkg/controller/certificate-shim/sync_test.go
Labels: size/L, release-note, approved, lgtm, area/api, dco-signoff: yes, ok-to-test, needs-kind

#6857 [Release 1.13] Bump github.com/go-jose/go-jose to v3.0.3 to fix CVE-2024-28180
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/cleanup, area/acme, dco-signoff: yes, area/testing

#6792 bugfix: LiteralSubject match function reports incorrect mismatch
  pkg/util/pki/match.go
  pkg/util/pki/match_test.go
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#6866 [release-1.14] ignore two false positive vulns
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6277 ControllerConfiguration fuzzer, only set the value in case the random value is empty
  internal/apis/config/controller/fuzzer/fuzzer.go
Labels: size/L, release-note-none, approved, lgtm, area/api, kind/cleanup, dco-signoff: yes, area/testing

#6723 Add new testcase that generates a non-critical SAN extension to the GenerateCSR tests
  pkg/util/pki/csr_test.go
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6870 chore: remove repetitive words
  internal/apis/certmanager/validation/util/nameserver_test.go
  pkg/controller/cainjector/setup.go
Labels: size/XS, release-note-none, approved, lgtm, needs-ok-to-test, dco-signoff: yes, needs-kind

#6868 [release-1.13] ignore two false positive vulns
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6869 [release-1.12] ignore two false positive vulns
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6871 BUGFIX: exit with correct exit codes
  internal/cmd/util/exit_test.go
  internal/cmd/util/signal.go
  internal/cmd/util/signal_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6865 Add user-agent header in requests to Venafi API
  pkg/controller/certificaterequests/venafi/venafi.go
  pkg/controller/certificaterequests/venafi/venafi_test.go
  pkg/controller/certificatesigningrequests/venafi/venafi.go
  pkg/controller/certificatesigningrequests/venafi/venafi_test.go
  pkg/issuer/venafi/client/venaficlient.go
  pkg/issuer/venafi/client/venaficlient_test.go
  pkg/issuer/venafi/setup.go
  pkg/issuer/venafi/setup_test.go
  pkg/issuer/venafi/venafi.go
  pkg/util/useragent.go
Labels: size/L, release-note, approved, lgtm, kind/feature, dco-signoff: yes
