Repository cert-manager/cert-manager, pull requests merged in 2024-04, with the labels that each got.

#6911 Makefile bugfix
  make/ci.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6915 re-add mistakenly removed make tidy target
  make/02_mod.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#6913 Better error issuerref
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/certificate_test.go
Labels: release-note, approved, lgtm, size/S, kind/feature, dco-signoff: yes

#6918 re-add removed targets, update base images
  make/02_mod.mk
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#6919 Run 'make upgrade-klone', fixing the self-upgrade script
  .github/dependabot.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/repository-base/base/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: size/L, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes

#6929 bump /x/net to fix CVE-2023-45288
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, area/testing

#6926 refactoring: remove unnecessary code
  hack/prune-junit-xml/prunexml_test.go
  internal/cmd/util/signal_test.go
  internal/controller/certificates/policies/checks_test.go
  pkg/apis/experimental/v1alpha1/types.go
  pkg/controller/certificate-shim/sync.go
  pkg/issuer/acme/dns/akamai/akamai.go
Labels: release-note-none, approved, lgtm, size/S, area/api, needs-ok-to-test, area/acme, dco-signoff: yes, area/acme/dns01, needs-kind

#6933 [release-1.12] fix CVE-2023-45288, bump base images, bump go
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/tools.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, area/testing

#6932 [release-1.13] fix CVE-2023-45288, bump base images, bump go
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/base_images.mk
  make/tools.mk
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/bug, area/acme, dco-signoff: yes, area/testing

#6906 Disable rclone gcs bucket ACL
  make/release.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6938 Remove docker custom network hack which has been moved to the test runner
  make/cluster.sh
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#6928 Add go makefile module
  .github/workflows/govulncheck.yaml
  .golangci.ci.yaml
  .golangci.yaml
  hack/verify-goimports.sh
  klone.yaml
  make/00_mod.mk
  make/_shared/go/.golangci.override.yaml
  make/_shared/go/01_mod.mk
  make/_shared/go/README.md
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/ci.mk
  test/e2e/suite/certificates/duplicatesecretname.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6942 [release-1.14] Disable rclone gcs bucket ACL
  make/release.mk
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6937 Upgrade repository-base module and disable dependabot
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/00_mod.mk
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/dependabot.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes, area/testing

#6889 feat: Adding API defaults unit test + testfile fixture
  internal/apis/config/cainjector/v1alpha1/defaults_test.go
  internal/apis/config/cainjector/v1alpha1/testdata/defaults.json
  internal/apis/config/controller/v1alpha1/defaults_test.go
  internal/apis/config/controller/v1alpha1/testdata/defaults.json
  internal/apis/config/webhook/v1alpha1/defaults_test.go
  internal/apis/config/webhook/v1alpha1/testdata/defaults.json
  make/test.mk
Labels: size/L, release-note-none, approved, lgtm, dco-signoff: yes, ok-to-test, needs-kind

#6927 Graduate 'DisallowInsecureCSRUsageDefinition' to GA
  internal/webhook/feature/features.go
  pkg/controller/certificaterequests/ca/ca.go
  pkg/controller/certificaterequests/selfsigned/selfsigned.go
Labels: release-note, approved, lgtm, size/S, dco-signoff: yes, ok-to-test, needs-kind

#6957 [release-1.12] ignore trivy false positive CVE-2020-8559
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6956 [release-1.13] ignore trivy false positive CVE-2020-8559
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6959 [Release v1.14.5] Update cmd/cmctl's go.mod to v1.14.5
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6954 ignore CVE-2020-8559 in trivy scans
  .trivyignore
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#6949 chore: remove repetitive words
  design/20190708.certificate-request-crd.md
  internal/controller/feature/features.go
  test/integration/certificates/issuing_controller_test.go
Labels: size/XS, release-note, approved, lgtm, kind/design, dco-signoff: yes, area/testing, ok-to-test

#6963 Graduate 'DisallowInsecureCSRUsageDefinition' to GA (part 2)
  .golangci.yaml
  internal/apis/certmanager/validation/certificaterequest.go
  internal/controller/feature/features.go
  internal/webhook/feature/features.go
  pkg/util/pki/certificatetemplate.go
  test/integration/validation/certificaterequest_test.go
Labels: size/L, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6967 Upgrade K8s dependencies to v0.30.0
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  deploy/crds/crd-challenges.yaml
  deploy/crds/crd-clusterissuers.yaml
  deploy/crds/crd-issuers.yaml
  go.mod
  go.sum
  hack/openapi_reports/acme.txt
  internal/apis/config/cainjector/v1alpha1/testdata/defaults.json
  internal/apis/config/controller/v1alpha1/testdata/defaults.json
  internal/apis/config/webhook/v1alpha1/testdata/defaults.json
  make/00_mod.mk
  pkg/acme/webhook/openapi/zz_generated.openapi.go
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing, area/deploy

#6970 Promote AdditionalCertificateOutputFormats feature gate to Beta
  deploy/crds/crd-certificates.yaml
  internal/apis/certmanager/types_certificate.go
  internal/controller/feature/features.go
  internal/webhook/feature/features.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/controller/certificates/issuing/internal/secret_test.go
  test/e2e/suite/certificates/additionaloutputformats.go
  test/e2e/suite/issuers/ca/certificate.go
  test/integration/certificates/issuing_controller_test.go
Labels: release-note, approved, lgtm, area/api, kind/feature, size/M, dco-signoff: yes, area/testing, area/deploy

#6972 Fix linters: misspell, gocritic, bodyclose, unused, unconvert, gosimple, ginkgolinter and wastedassign
  .golangci.yaml
  cmd/controller/app/options/options_test.go
  cmd/controller/app/start.go
  hack/extractcrd/main.go
  internal/apis/certmanager/validation/certificate.go
  internal/apis/certmanager/validation/issuer.go
  internal/apis/certmanager/validation/issuer_test.go
  internal/controller/certificates/policies/checks.go
  internal/vault/vault.go
  internal/vault/vault_test.go
  make/config/samplewebhook/sample/main.go
  pkg/acme/util.go
  pkg/controller/acmechallenges/controller_test.go
  pkg/controller/acmechallenges/sync.go
  pkg/controller/acmeorders/sync.go
  pkg/controller/certificate-shim/gateways/controller.go
  pkg/controller/certificate-shim/sync.go
  pkg/controller/certificate-shim/sync_test.go
  pkg/controller/certificaterequests/ca/ca.go
  pkg/controller/certificaterequests/controller.go
  pkg/controller/certificates/issuing/issuing_controller.go
  pkg/controller/certificates/issuing/secret_manager.go
  pkg/controller/certificates/readiness/readiness_controller.go
  pkg/controller/certificates/readiness/readiness_controller_test.go
  pkg/controller/certificates/trigger/trigger_controller.go
  pkg/controller/certificatesigningrequests/controller.go
  pkg/controller/certificatesigningrequests/vault/vault.go
  pkg/issuer/acme/dns/azuredns/azuredns.go
  pkg/issuer/acme/dns/cloudflare/cloudflare.go
  pkg/issuer/acme/dns/cloudflare/cloudflare_test.go
  pkg/issuer/vault/setup_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/server/tls/dynamic_source.go
  pkg/server/tls/dynamic_source_test.go
  pkg/util/cmapichecker/cmapichecker_test.go
  pkg/util/configfile/configfile.go
  pkg/util/pki/asn1_util.go
  pkg/util/pki/certificatetemplate.go
  pkg/util/pki/match_test.go
  pkg/util/pki/sans.go
  pkg/util/pki/subject.go
  test/e2e/bin/cloudflare-clean/main.go
  test/e2e/framework/addon/chart/addon.go
  test/e2e/framework/helper/certificaterequests.go
  test/e2e/framework/helper/featureset/featureset.go
  test/e2e/framework/matcher/san_matchers.go
  test/e2e/framework/util.go
  test/e2e/suite/certificaterequests/approval/approval.go
  test/e2e/suite/certificaterequests/approval/userinfo.go
  test/e2e/suite/certificates/additionaloutputformats.go
  test/e2e/suite/certificates/literalsubjectrdns.go
  test/e2e/suite/certificates/othernamesan.go
  test/e2e/suite/conformance/certificates/tests.go
  test/e2e/suite/conformance/certificatesigningrequests/tests.go
  test/e2e/suite/issuers/acme/certificate/webhook.go
  test/e2e/suite/issuers/acme/certificaterequest/dns01.go
  test/e2e/suite/serving/cainjector.go
  test/e2e/util/util.go
  test/integration/certificates/metrics_controller_test.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, area/acme, area/vault, dco-signoff: yes, area/testing, area/acme/dns01
