Repository cert-manager/cert-manager, pull requests merged in 2024-06, with the labels that each got.

#7069 Enable Helm values.yaml jsonschema validation
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/_helpers.tpl
  deploy/charts/cert-manager/templates/podmonitor.yaml
  deploy/charts/cert-manager/values.linter.exceptions
  deploy/charts/cert-manager/values.schema.json
  deploy/charts/cert-manager/values.yaml
  make/ci.mk
  make/manifests.mk
Labels: release-note, approved, lgtm, kind/feature, size/XXL, dco-signoff: yes, area/deploy

#7057 Startupapicheck: validate that the validating and mutating webhooks are doing their job
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/startupapicheck/pkg/check/api/api.go
  cmd/webhook/go.mod
  deploy/charts/cert-manager/templates/startupapicheck-rbac.yaml
  pkg/util/cmapichecker/cmapichecker.go
  pkg/util/cmapichecker/cmapichecker_test.go
Labels: release-note, size/XL, approved, lgtm, kind/bug, dco-signoff: yes, area/deploy

#7100 Cleanup test helpers by increasing usage of gen package.
  internal/apis/certmanager/validation/certificaterequest_test.go
  pkg/controller/certificates/requestmanager/util_test.go
  pkg/util/pki/match_test.go
  test/e2e/suite/issuers/acme/certificaterequest/dns01.go
  test/e2e/suite/issuers/acme/certificaterequest/http01.go
  test/e2e/suite/issuers/ca/certificaterequest.go
  test/e2e/suite/issuers/vault/certificaterequest/approle.go
  test/e2e/suite/issuers/venafi/tpp/certificaterequest.go
  test/e2e/util/util.go
  test/integration/certificates/issuing_controller_test.go
  test/integration/certificates/revisionmanager_controller_test.go
  test/integration/validation/certificaterequest_test.go
  test/unit/gen/csr.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#7094 Upgrade dependencies
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  go.mod
  go.sum
  make/config/projectcontour/contour.yaml
  make/config/projectcontour/gateway.yaml
  make/e2e-setup.mk
  pkg/issuer/acme/dns/route53/route53_test.go
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing, area/acme/dns01

#7109 [release-1.12] bump go-jose to fix CVE alert
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
Labels: size/L, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#7111 [release-1.15] BUGFIX: retry signing when encountering transient error (Vault issuer)
  internal/vault/vault.go
  pkg/controller/certificaterequests/vault/vault.go
  pkg/controller/certificaterequests/vault/vault_test.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#7116 [release-1.14] Update cmd/cmctl's go.mod to v1.14.7
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, needs-kind

#7115 [release-1.12] Update cmd/cmctl's go.mod to v1.12.12
  cmd/ctl/go.mod
  cmd/ctl/go.sum
  test/integration/go.mod
Labels: release-note-none, approved, lgtm, size/M, dco-signoff: yes, area/testing, needs-kind

#7110 Simplify CertificateSigningRequest conformance tests and add missing tests
  test/e2e/framework/helper/validation/certificatesigningrequests/certificatesigningrequests.go
  test/e2e/framework/util.go
  test/e2e/suite/certificates/additionaloutputformats.go
  test/e2e/suite/certificates/literalsubjectrdns.go
  test/e2e/suite/certificates/othernamesan.go
  test/e2e/suite/certificatesigningrequests/selfsigned/selfsigned.go
  test/e2e/suite/conformance/certificates/tests.go
  test/e2e/suite/conformance/certificatesigningrequests/acme/acme.go
  test/e2e/suite/conformance/certificatesigningrequests/suite.go
  test/e2e/suite/conformance/certificatesigningrequests/tests.go
  test/e2e/suite/conformance/certificatesigningrequests/vault/approle.go
  test/e2e/suite/conformance/certificatesigningrequests/vault/kubernetes.go
  test/e2e/suite/issuers/ca/certificate.go
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, area/testing

#6966 Add process and go runtime metrics for controller
  pkg/metrics/metrics.go
  test/integration/certificates/metrics_controller_test.go
Labels: release-note, approved, lgtm, size/S, kind/feature, dco-signoff: yes, area/testing, ok-to-test, area/monitoring

#7119 Fix Venafi conformance test
  test/e2e/suite/conformance/certificatesigningrequests/tests.go
Labels: size/XS, release-note-none, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#7106 Refactor Certificate conformance to tabular tests
  test/e2e/framework/helper/validation/certificates/certificates.go
  test/e2e/suite/conformance/certificates/suite.go
  test/e2e/suite/conformance/certificates/tests.go
  test/unit/gen/certificate.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, dco-signoff: yes, area/testing

#7124 make e2e-setup-certmanager: E2E_CERT_MANAGER_VERSION now works
  make/e2e-setup.mk
Labels: size/XS, release-note-none, approved, lgtm, dco-signoff: yes, needs-kind

#7125 Bump go-retryablehttp to address CVE-2024-6104
  cmd/controller/go.mod
  cmd/controller/go.sum
  go.mod
  go.sum
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes

#7128 [release-1.12] Bump go-retryablehttp to address CVE-2024-6104
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes, area/testing

#7127 [release-1.14] Bump go-retryablehttp to address CVE-2024-6104
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/ctl/LICENSES
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
  test/integration/LICENSES
  test/integration/go.mod
  test/integration/go.sum
Labels: size/L, release-note, approved, lgtm, kind/bug, dco-signoff: yes, area/testing

#7130 [release-1.15] Bump go-retryablehttp to address CVE-2024-6104
  LICENSES
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  go.mod
  go.sum
  test/e2e/LICENSES
  test/e2e/go.mod
  test/e2e/go.sum
Labels: release-note, approved, lgtm, size/S, kind/bug, dco-signoff: yes, area/testing

#7140 BUGFIX: Venafi issuer and clusterissuer checks were failing due to nilpointer exception
  pkg/controller/clusterissuers/checks.go
  pkg/controller/issuers/checks.go
Labels: release-note-none, approved, lgtm, size/S, kind/bug, dco-signoff: yes, area/venafi
