Repository cert-manager/cert-manager, pull requests merged in 2025-08, with the labels that each got.

#7414 feat: API defaults for IssuerRef
  deploy/charts/cert-manager/templates/crd-acme.cert-manager.io_challenges.yaml
  deploy/charts/cert-manager/templates/crd-acme.cert-manager.io_orders.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_certificaterequests.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_certificates.yaml
  deploy/crds/acme.cert-manager.io_challenges.yaml
  deploy/crds/acme.cert-manager.io_orders.yaml
  deploy/crds/cert-manager.io_certificaterequests.yaml
  deploy/crds/cert-manager.io_certificates.yaml
  internal/apis/acme/fuzzer/fuzzer.go
  internal/apis/acme/types_challenge.go
  internal/apis/acme/types_order.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/v1/zz_generated.defaults.go
  internal/apis/certmanager/fuzzer/fuzzer.go
  internal/apis/certmanager/types_certificate.go
  internal/apis/certmanager/types_certificaterequest.go
  internal/apis/certmanager/v1/zz_generated.conversion.go
  internal/apis/certmanager/v1/zz_generated.defaults.go
  internal/apis/meta/types.go
  internal/apis/meta/v1/conversion.go
  internal/apis/meta/v1/zz_generated.conversion.go
  internal/apis/meta/zz_generated.deepcopy.go
  internal/generated/openapi/zz_generated.openapi.go
  pkg/apis/acme/v1/types_challenge.go
  pkg/apis/acme/v1/types_order.go
  pkg/apis/certmanager/v1/types_certificate.go
  pkg/apis/certmanager/v1/types_certificaterequest.go
  pkg/apis/meta/v1/types.go
  pkg/apis/meta/v1/zz_generated.deepcopy.go
  pkg/client/applyconfigurations/acme/v1/challengespec.go
  pkg/client/applyconfigurations/acme/v1/orderspec.go
  pkg/client/applyconfigurations/certmanager/v1/certificaterequestspec.go
  pkg/client/applyconfigurations/certmanager/v1/certificatespec.go
  pkg/client/applyconfigurations/internal/internal.go
  pkg/client/applyconfigurations/meta/v1/issuerreference.go
  pkg/client/applyconfigurations/utils.go
Labels: size/L, release-note, approved, lgtm, area/api, kind/feature, area/acme, dco-signoff: yes, area/testing, area/acme/dns01, area/monitoring, area/deploy

#7869 Migrate away from deprecated fake NewSimpleClientset func
  pkg/controller/acmechallenges/scheduler/scheduler_test.go
  pkg/controller/acmechallenges/update_test.go
  pkg/controller/certificates/requestmanager/requestmanager_controller_test.go
  pkg/controller/test/actions.go
  pkg/controller/test/context_builder.go
  pkg/issuer/acme/http/ingress_test.go
  pkg/issuer/vault/setup_test.go
  pkg/metrics/metrics_test.go
  pkg/server/tls/authority/authority_test.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, area/acme, area/vault, dco-signoff: yes, area/acme/http01, area/monitoring

#7902 Upgrade images
  make/base_images.mk
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#7917 Revert "Re-enable Dependabot upgrades"
  .github/dependabot.yaml
  make/00_mod.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#7919 Improve script generating applyconfigurations
  hack/k8s-codegen.sh
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#7925 bug(ci): renovate config fixes
  .github/renovate.json5
  .github/workflows/renovate.yml
Labels: release-note-none, approved, lgtm, kind/bug, size/M, dco-signoff: yes, ok-to-test

#7926 bug(ci): escaping new lines in json5
  .github/renovate.json5
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, ok-to-test

#7929 fix(ci): new improvements on renovate config
  .github/renovate.json5
  .github/workflows/renovate.yml
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#7958 ci(renovate): disable scheduled job
  .github/workflows/renovate.yml
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#7967 [release-1.17] increase maximum PEM sizes for leaf certificates and chains
  internal/pem/decode.go
  internal/pem/decode_test.go
  pkg/util/pki/parse_certificate_chain_test.go
Labels: release-note, approved, lgtm, kind/bug, size/M, dco-signoff: yes

#7761 Helm: Fix naming format of tokenrequest RBAC resources
  deploy/charts/cert-manager/templates/rbac.yaml
Labels: size/XS, release-note, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test, area/deploy

#7985 fix(ci): dont separate major minor
  .github/renovate.json5
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#8005 Enable makefile-modules Dependabot/Renovate
  .github/dependabot.yaml
  .github/renovate.json5
  .github/workflows/renovate.yaml
  make/00_mod.mk
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#8021 fix: Enforce strict mutual exclusion for HTTP-01 ingress configuration fields
  internal/apis/certmanager/validation/issuer.go
  internal/apis/certmanager/validation/issuer_test.go
Labels: release-note, approved, lgtm, kind/bug, size/M, area/acme, dco-signoff: yes, ok-to-test, area/acme/http01
