Repository cert-manager/cert-manager, pull requests merged in 2025-09, with the labels that each got.

#8018 fix(deps): upgrade Kubernetes to 1.34
  LICENSES
  cmd/acmesolver/LICENSES
  cmd/acmesolver/go.mod
  cmd/acmesolver/go.sum
  cmd/cainjector/LICENSES
  cmd/cainjector/go.mod
  cmd/cainjector/go.sum
  cmd/controller/LICENSES
  cmd/controller/go.mod
  cmd/controller/go.sum
  cmd/startupapicheck/LICENSES
  cmd/startupapicheck/go.mod
  cmd/startupapicheck/go.sum
  cmd/webhook/LICENSES
  cmd/webhook/go.mod
  cmd/webhook/go.sum
  deploy/charts/cert-manager/templates/crd-acme.cert-manager.io_challenges.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_clusterissuers.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_issuers.yaml
  deploy/crds/acme.cert-manager.io_challenges.yaml
  deploy/crds/cert-manager.io_clusterissuers.yaml
  deploy/crds/cert-manager.io_issuers.yaml
  go.mod
  go.sum
  hack/openapi_reports/client.txt
  internal/controller/certificaterequests/apply_test.go
  internal/controller/certificates/apply_test.go
  internal/controller/certificates/policies/checks.go
  internal/controller/challenges/apply_test.go
  internal/controller/issuers/apply_test.go
  internal/controller/orders/apply_test.go
  internal/generated/openapi/zz_generated.openapi.go
  make/00_mod.mk
  pkg/client/applyconfigurations/acme/v1/challenge.go
  pkg/client/applyconfigurations/acme/v1/order.go
  pkg/client/applyconfigurations/certmanager/v1/certificate.go
  pkg/client/applyconfigurations/certmanager/v1/certificaterequest.go
  pkg/client/applyconfigurations/certmanager/v1/clusterissuer.go
  pkg/client/applyconfigurations/certmanager/v1/issuer.go
  pkg/client/applyconfigurations/internal/internal.go
  pkg/client/applyconfigurations/utils.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/controller/certificate-shim/sync_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/suite/certificates/additionaloutputformats.go
  test/e2e/suite/certificates/secrettemplate.go
  test/e2e/util/util.go
  test/integration/go.mod
  test/integration/go.sum
Labels: release-note-none, approved, lgtm, kind/cleanup, size/XXL, area/acme, dco-signoff: yes, area/testing, area/deploy

#8037 [CI] Self-upgrade merging self-upgrade-master into master
  .github/chainguard/make-self-upgrade.sts.yaml
  .github/chainguard/renovate.sts.yaml
  .github/dependabot.yaml
  .github/renovate.json5
  .github/workflows/make-self-upgrade.yaml
  .github/workflows/renovate.yaml
  klone.yaml
  make/_shared/repository-base/01_mod.mk
  make/_shared/repository-base/base-dependabot/.github/dependabot.yaml
  make/_shared/repository-base/base-dependabot/.github/renovate.json5
  make/_shared/repository-base/base-dependabot/.github/workflows/renovate.yaml
  make/_shared/repository-base/base/.github/chainguard/make-self-upgrade.sts.yaml
  make/_shared/repository-base/base/.github/chainguard/renovate.sts.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: size/L, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#8050 fix: typo in SecretTemplateMismatch's comment
  internal/controller/certificates/policies/constants.go
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, tide/merge-method-squash, ok-to-test

#8073 fix(ci): upgrading to v1.34 for CI and local tests
  make/cluster.sh
  make/e2e-setup.mk
  make/kind_images.sh
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#7973 feat(deploy/chart): adding hostUsers property to pods
  deploy/charts/cert-manager/README.template.md
  deploy/charts/cert-manager/templates/cainjector-deployment.yaml
  deploy/charts/cert-manager/templates/deployment.yaml
  deploy/charts/cert-manager/templates/startupapicheck-job.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
  deploy/charts/cert-manager/values.schema.json
  deploy/charts/cert-manager/values.yaml
Labels: release-note, approved, lgtm, do-not-merge/hold, kind/feature, size/M, area/acme, dco-signoff: yes, area/testing, tide/merge-method-squash, area/deploy

#7972 feat: Add resource requirements support to ACME HTTP01 solver pod templates
  deploy/charts/cert-manager/templates/crd-acme.cert-manager.io_challenges.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_clusterissuers.yaml
  deploy/charts/cert-manager/templates/crd-cert-manager.io_issuers.yaml
  deploy/crds/acme.cert-manager.io_challenges.yaml
  deploy/crds/cert-manager.io_clusterissuers.yaml
  deploy/crds/cert-manager.io_issuers.yaml
  internal/apis/acme/types_issuer.go
  internal/apis/acme/v1/zz_generated.conversion.go
  internal/apis/acme/zz_generated.deepcopy.go
  internal/generated/openapi/zz_generated.openapi.go
  pkg/apis/acme/v1/types_issuer.go
  pkg/apis/acme/v1/zz_generated.deepcopy.go
  pkg/client/applyconfigurations/acme/v1/acmechallengesolverhttp01ingresspodresources.go
  pkg/client/applyconfigurations/acme/v1/acmechallengesolverhttp01ingresspodspec.go
  pkg/client/applyconfigurations/internal/internal.go
  pkg/client/applyconfigurations/utils.go
  pkg/issuer/acme/http/pod.go
  pkg/issuer/acme/http/pod_test.go
Labels: release-note, size/XL, approved, lgtm, area/api, kind/feature, area/acme, dco-signoff: yes, ok-to-test, area/acme/http01, area/deploy

#8089 Add missing labels to Renovate PRs
  .github/renovate.json5
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes

#8092 refactor: use maps.Copy for cleaner map handling
  pkg/controller/certificate-shim/sync.go
  pkg/controller/certificates/issuing/internal/secret.go
  pkg/controller/certificates/requestmanager/util_test.go
  pkg/issuer/acme/http/httproute.go
  pkg/issuer/acme/http/ingress.go
  pkg/issuer/acme/http/pod.go
Labels: release-note, approved, lgtm, kind/cleanup, needs-ok-to-test, size/M, area/acme, dco-signoff: yes, area/acme/http01

#8093 chore(helm chart): Fix empty lines, and spaces found by yamllint
  deploy/charts/cert-manager/templates/rbac.yaml
  deploy/charts/cert-manager/templates/webhook-deployment.yaml
Labels: size/XS, release-note-none, approved, lgtm, kind/cleanup, dco-signoff: yes, ok-to-test, area/deploy

#8083 asn1_util: flatten the MarshalUniversalValue func
  pkg/util/pki/asn1_util.go
Labels: release-note-none, approved, lgtm, kind/cleanup, size/M, dco-signoff: yes

#8072 feat: log version information when starting the cert-manager controller, webhook and ca-injector
  cmd/cainjector/app/cainjector.go
  cmd/controller/app/controller.go
  cmd/controller/app/start.go
  cmd/webhook/app/webhook.go
Labels: release-note, approved, lgtm, size/S, kind/feature, dco-signoff: yes, ok-to-test, cybr

#8096 Make Renovate suggest base image updates
  .github/renovate.json5
  make/base_images.mk
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes

#8120 fix(e2e): upgrading cloudflare deps to v6
  test/e2e/bin/cloudflare-clean/main.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: release-note-none, approved, lgtm, size/S, kind/cleanup, dco-signoff: yes, area/testing
